### ISSUE TITLE
Test coverage: net.neurons() not being covered in test set

### ISSUE THREAD

**Issue by slarson** [openworm/PyOpenWorm#103]
@gsarma FYI -- this might be something to look into.  Check out issue #102 for the error that should be covered in a test.

**Comment by gsarma** [comment]
Added test with @travs.  Will commit as soon as I have commit privileges.

**Comment by slarson** [comment]
great!  please use the [pull request mechanism](https://openworm.readthedocs.org/en/latest/Community/github/index.html?highlight=pull%20request#forking-github-repositories) for now
