### ISSUE TITLE
Test coverage: neuropeptide test

### ISSUE THREAD

**Issue by slarson** [openworm/PyOpenWorm#106]
We should have a test that verifies that we get "True" out of this.  cc: @gsarma @travs 

Related to issue #105 
```
  >>> n = P.Neuron()
  >>> n.neuropeptide("TH")
  neuropeptide=`TH'

  >>> s = set(x.name() for x in n.load()) 
  >>> s == set(['CEPDR', 'PDER', 'CEPDL', 'PDEL', 'CEPVR', 'CEPVL'])
  True
```

**Comment by gsarma** [comment]
Added test with @travs.  Will commit as soon as I have commit privileges.

**Comment by slarson** [comment]
great!  please use the [pull request mechanism](https://openworm.readthedocs.org/en/latest/Community/github/index.html?highlight=pull%20request#forking-github-repositories) for now
