### ISSUE TITLE
Examples don't run correctly until tests are run

### ISSUE THREAD

**Issue by pgleeson** [openworm/PyOpenWorm#113]
I tried the examples here: https://github.com/openworm/PyOpenWorm/tree/alpha0.5/examples on my machine after successfully running: sudo python setup.py install

Initially (with me being too lazy to read documentation) the examples gave cryptic errors like:

> python NeuronBasicInfo.py 
Retrieving names...
Traceback (most recent call last):
  File "NeuronBasicInfo.py", line 32, in <module>
    inter = get_names(net.interneurons())
AttributeError: 'NoneType' object has no attribute 'interneurons'

I realized then that a database had to be generated but the [README](https://github.com/openworm/PyOpenWorm/tree/alpha0.5/examples) wasn't very clear.

However running the tests at the top level using 

     python tests/test.py

created the database & I could run the examples

Would be great if there was a more informative error on missing database & if there was a quick start guide in the examples folder.

**Comment by travs** [comment]
Right, IMO the database should be generated when the install script is run (i.e. `insert_worm.py` should be run).

**Comment by slarson** [comment]
@travs yes -- I don't see why not.  This would probably be preferable to #79 and would resolve it.  Made #120 for this.

**Comment by pgleeson** [comment]
Great! I really think it would be best if the user gets to the point they can use default/core features as quickly as possible. They can customise it later with other data sources etc. if needed.

**Comment by slarson** [comment]
Should be solved with #121 -- reopen if not.

**Comment by slarson** [comment]
@pgleeson reports:

Great! However, if you install with:

    sudo python setup.py install

you get a permission error:

    IOError: [Errno 13] Permission denied: '/home/padraig/temp/PyOpenWorm/worm.db.lock'

Maybe change read/write permissions of worm.db? 

Is this the best place for this btw, not /usr/local/lib/python2.7/dist-packages/PyOpenWorm? It seems python scripts run from other dirs can't find worm.db...

**Comment by travs** [comment]
@pgleeson [this](http://stackoverflow.com/questions/14861634/how-do-i-distribute-data-files-with-a-python-package-such-that-theyre-readable) may also be related.

**Comment by travs** [comment]
@pgleeson Also, what OS are you on? I want to try and recreate it

**Comment by pgleeson** [comment]
On Ubuntu. Basically if I run sudo python setup.py install, the following permissions are on the generated files:
>
drwxrwxr-x 11 padraig padraig    4096 Jun  4 14:30 .
-rw-r--r--  1 root    root      68912 Jun  4 14:30 worm.db.index
-rw-r--r--  1 root    root    5501476 Jun  4 14:30 worm.db
-rw-r--r--  1 root    root    1078832 Jun  4 14:30 worm.db.tmp
-rw-r--r--  1 root    root          6 Jun  4 14:30 worm.db.lock
drwxr-xr-x  2 root    root       4096 Jun  4 14:30 PyOpenWorm.egg-info
drwxr-xr-x  3 root    root       4096 Jun  4 14:30 build
drwxrwxr-x  8 padraig padraig    4096 Jun  4 14:29 .git
drwxrwxr-x  2 padraig padraig    4096 Jun  4 14:29 tests
drwxrwxr-x  2 padraig padraig    4096 Jun  4 14:29 docs
...

i.e. root is the only one with write permissions on worm.db*. If I run a script as padraig, I can't change that file. 

Should just be a case of giving write permission for these to all users for:
/home/user/PyOpenWorm/worm.db*
or (if installed for use by scripts in any dir)
/usr/local/lib/python2.7/dist-packages/PyOpenWorm/worm.db*

**Comment by travs** [comment]
@pgleeson 

Ok, I was able to get this error on Ubuntu, but it is not as simple as it seems unfortunately.

Something in PyOpenWorm creates a file called `worm.db.index.index_tmp` *while* the database is connected to, apparently. This file doesn't have `rw` privileges for the non-root user, and since it's a temporary file (and I don't yet know how it's created), I'm not sure how this could be remedied yet.

@pgleeson Any ideas? 

Below is my session output.

```bash
┌─[travis][travis-VirtualBox][~]
└─▪ ll /usr/local/lib/python2.7/dist-packages/PyOpenWorm-0.5.0_alpha-py2.7.egg/PyOpenWorm/worm.db*
-rwxrwxrwx 1 root staff 45897634 Jun  4 21:25 /usr/local/lib/python2.7/dist-packages/PyOpenWorm-0.5.0_alpha-py2.7.egg/PyOpenWorm/worm.db
-rwxrwxrwx 1 root staff   235000 Jun  4 21:25 /usr/local/lib/python2.7/dist-packages/PyOpenWorm-0.5.0_alpha-py2.7.egg/PyOpenWorm/worm.db.index
-rwxrwxrwx 1 root staff        7 Jun  4 21:26 /usr/local/lib/python2.7/dist-packages/PyOpenWorm-0.5.0_alpha-py2.7.egg/PyOpenWorm/worm.db.lock
-rwxrwxrwx 1 root staff        0 Jun  4 21:26 /usr/local/lib/python2.7/dist-packages/PyOpenWorm-0.5.0_alpha-py2.7.egg/PyOpenWorm/worm.db.tmp
┌─[travis][travis-VirtualBox][~]
└─▪ python -c 'import PyOpenWorm as P; P.connect()'
INFO:rdflib:RDFLib Version: 4.2.0
/usr/local/lib/python2.7/dist-packages/PyOpenWorm-0.5.0_alpha-py2.7.egg/PyOpenWorm/default.conf
INFO:root:Connected to database
ERROR:ZODB.FileStorage:Error saving index on close()
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ZODB-4.1.0-py2.7.egg/ZODB/FileStorage/FileStorage.py", line 429, in close
    self._save_index()
  File "/usr/local/lib/python2.7/dist-packages/ZODB-4.1.0-py2.7.egg/ZODB/FileStorage/FileStorage.py", line 286, in _save_index
    self._index.save(self._pos, tmp_name)
  File "/usr/local/lib/python2.7/dist-packages/ZODB-4.1.0-py2.7.egg/ZODB/fsIndex.py", line 112, in save
    with open(fname, 'wb') as f:
IOError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/PyOpenWorm-0.5.0_alpha-py2.7.egg/PyOpenWorm/worm.db.index.index_tmp'
```

**Comment by pgleeson** [comment]
Maybe make a sub folder dist-packages/PyOpenWorm/database and change just that folder to have write permissions for all? 

Alternatively (since there could in theory be multiple users on a system that want to do different things with PyOpenWorm) have the database in /home/user/.PyOpenWorm? Then the scripts can find the database from whereever they're run. The disadvantage is that root won't create this by default in sudo python setup... In this case there should be a more explicit warning at command line when the database is not initialised, and advice given on how to do that (e.g. create a script, init_pyopenworm using [entry_points in setup.py](https://github.com/NeuroML/pyNeuroML/blob/master/setup.py#L12) that can be run once by a user to setup the database).

**Comment by slarson** [comment]
Should be fixed by #125

**Comment by pgleeson** [comment]
Still have trouble with this... Installs fine & copies database files to local PyOpenWorm dir, with correct permissions:
> 
padraig@avicenna2:~/PyOpenWorm$ sudo python setup.py install
....
copying /home/padraig/PyOpenWorm/OpenWormData/scripts/worm.db.tmp to /home/padraig/PyOpenWorm/PyOpenWorm
copying /home/padraig/PyOpenWorm/OpenWormData/scripts/worm.db.lock to /home/padraig/PyOpenWorm/PyOpenWorm
copying /home/padraig/PyOpenWorm/OpenWormData/scripts/worm.db to /home/padraig/PyOpenWorm/PyOpenWorm
copying /home/padraig/PyOpenWorm/OpenWormData/scripts/worm.db.index to /home/padraig/PyOpenWorm/PyOpenWorm

but when I try:

    cd examples/
    python NetworkInfo.py

I get:

>
Connecting to the database...
Traceback (most recent call last):
  File "NetworkInfo.py", line 19, in <module>
    P.connect()
  File "/usr/local/lib/python2.7/dist-packages/PyOpenWorm-0.5.0_alpha-py2.7.egg/PyOpenWorm/__init__.py", line 194, in connect
    Configureable.conf.openDatabase()
  File "/usr/local/lib/python2.7/dist-packages/PyOpenWorm-0.5.0_alpha-py2.7.egg/PyOpenWorm/data.py", line 252, in openDatabase
    self.source.open()
  File "/usr/local/lib/python2.7/dist-packages/PyOpenWorm-0.5.0_alpha-py2.7.egg/PyOpenWorm/data.py", line 569, in open
    fs=FileStorage(openstr)
  File "/usr/local/lib/python2.7/dist-packages/ZODB-4.1.0-py2.7.egg/ZODB/FileStorage/FileStorage.py", line 164, in __init__
    self._lock_file = LockFile(file_name + '.lock')
  File "/usr/local/lib/python2.7/dist-packages/zc/lockfile/__init__.py", line 81, in __init__
    fp = open(path, 'a+')
IOError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/PyOpenWorm-0.5.0_alpha-py2.7.egg/PyOpenWorm/worm.db.lock'

i.e. assuming worm.db files are in install directory.

**Comment by travs** [comment]
Right. The issue here is the way that `PyOpenWorm/__init__.py` finds the `dist-packages` or `site-package` directory. I had fixed it for `sudo`, but didn't consider Ubuntu, which seems to be a special case (it uses `dist-packages` rather than `site-packages`). 

There are probably other cases analogous to this, so I'm coming up with something completely cross-platform now.

**Comment by travs** [comment]
Ok, [the latest commit on my fork](https://github.com/travs/PyOpenWorm/commit/c329e87ea59dee97a0907c23075b26bd9088635b) fixes this issue.

Tried it in an Ubuntu VM (using `sudo`)

**Comment by pgleeson** [comment]
I've tested locally and it works fine. Great work guys.
