### ISSUE TITLE
Tests for catching performance regressions

### ISSUE THREAD

**Issue by gsarma** [openworm/PyOpenWorm#114]
This is relevant for all sub-modules, but in particular, @travs mentions that this might be especially useful for PyOpenWorm.  See, for example, #42, #90, #21.  

This is not high priority, but after we have a much more mature testing workflow, we should incorporate these kinds of tests.  

A simple trick for writing tests that can reliably catch performance regressions across machine:  benchmark function performance with respect to a reference computation.  For example, if some simple arithmetic operation takes about a second, then we can use that as a reference unit that should be somewhat stable across different machine configurations.  It's also worth thinking about memory consumption, but that is probably less important at first.  

If we want to more rigorously characterize a machine, another thing to do would be to have a list of reference computations, and then use some kind of curve fitting to develop a machine-independent benchmark.  May or may not be useful in practice, but possibly worth looking into.

**Comment by slarson** [comment]
+1. This would be very helpful.  I would suggest googling around for a good
python framework for this.

**Comment by slarson** [comment]
@ kevcmk check this out

**Comment by cheelee** [comment]
This really ought to be right in my alley for research on performance tools, but strangely enough I do not recall any research work done for automatically comparing the performance profiles of two simulation experiments for regression purposes! We've always done this manually, and never thought much more about it ... I'm going to have to dig around at the performance analysis literature ... someone must have thought about this problem before.

**Comment by gsarma** [comment]
It doesn't need to be very complicated- even if we just verify that we are within 10-15% of past performance, it should be useful.  

Ultimately, when we have a really clean way of working with past profiling information, we should have some kind of anomaly detection framework.

**Comment by cheelee** [comment]
I agree. In its most general form, I think this is a very difficult problem. I'm still surprised I cannot find much in the way of literature on this after an early attempt. Of course the HPC folks focus on the problem of performance prediction on new architectures, so it is related but not the same as the ability to pick out detailed performance anomalies between different execution configurations across time, architecture, and experiment parameters.

Anyway, it is a good idea to start simple and then grow it according to our needs. If we develop techniques that are worth publication, it'd be a bonus :)

**Comment by kevcmk** [comment]
For reference, @cheelee 's cProfile script gist

https://gist.github.com/cheelee/03a8b60454d57ab3820d

**Comment by kevcmk** [comment]
and instructions for using it:

https://gist.github.com/cheelee/aaa73d44c8e82b8c3730

**Comment by travs** [comment]
@cheelee Is this included in your pull request?

**Comment by cheelee** [comment]
@travs Hey, yes. Both are. @kevcmk will have more elegant code for automatically handling the collection of performance data as well as structuring them for subsequent regression analysis soon.

**Comment by kevcmk** [comment]
#198

**Comment by mwatts15** [comment]
Performance tests are written, so closing this now.
