### ISSUE TITLE
Add switch/argument to Syn_degree to indicate whether pairs or pair incidences are desired

### ISSUE THREAD

**Issue by travs** [openworm/PyOpenWorm#118]
[This function](https://github.com/openworm/PyOpenWorm/blob/alpha0.5/PyOpenWorm/neuron.py#L195-L205) could return either the number of pairs or the number of pair incidences (much higher).

**Comment by mwatts15** [comment]
It's not clear what this is supposed to mean (are we increasing the count by the Connection.number rather than just by 1 or are we double counting when there's a Connection entry going from/to the same cell) or what specific need there is that `Neuron::connection::count`does not meet.
