### ISSUE TITLE
The database should be generated when the install script is run (i.e. insert_worm.py should be run)

### ISSUE THREAD

**Issue by slarson** [openworm/PyOpenWorm#120]

**Comment by slarson** [comment]
Closed with #121

**Comment by pgleeson** [comment]
Great! However, if you install with:

    sudo python setup.py install

you get a permission error:

    IOError: [Errno 13] Permission denied: '/home/padraig/temp/PyOpenWorm/worm.db.lock'

Maybe change read/write permissions of worm.db? 

Is this the best place for this btw, not /usr/local/lib/python2.7/dist-packages/PyOpenWorm? It seems python scripts run from other dirs can't find worm.db...

**Comment by travs** [comment]
@pgleeson unable to recreate locally.

I have gotten a  similar error when I had an active connection to the database and tried to modify the database from another source. I'm not sure what's happening is your case though, so could you grab a more complete error output?

Also, regarding location of db, you may be correct. Can you post an example?

**Comment by slarson** [comment]
This particular issue should be closed b/c the database is generated when installed.  However, the examples still not working, which @pgleeson points out, is issue #113, which I will reopen instead.
