### ISSUE TITLE
Make database accessible to other modules that use PyOpenWorm as a library

### ISSUE THREAD

**Issue by travs** [openworm/PyOpenWorm#124]
Raised by @pgleeson in #120.

We should put the created database somewhere accessible by external modules requiring PyOpenWorm as a library. This probably requires changing the default config file as well.

[This may also be related](http://stackoverflow.com/questions/14861634/how-do-i-distribute-data-files-with-a-python-package-such-that-theyre-readable).

**Comment by slarson** [comment]
Fixed by #125
