### ISSUE TITLE
Assert multiple things at once with the same piece of Evidence

### ISSUE THREAD

**Issue by travs** [openworm/PyOpenWorm#126]
Currently we have to do something like this to assert multiple statements:

```
# for some Neuron object avdl
>>> e.asserts(avdl)
asserts=`AVDL'
>>> e.asserts(avdl.lineageName)
asserts=`lineageName=`AB alaaapalr'';`AVDL'
```

A slight convenience (and easy fix) would be to instead have multiple arguments:

```
>>> e.asserts(avdl, avdl.lineageName) # could support any number of args
asserts=`lineageName=`AB alaaapalr'';`AVDL'
```

**Comment by mwatts15** [comment]
Given that the Context, which by definition supports 0..* statements is now the typical target of an `Evidence::suports`, this kind of syntactic sugar has limited utility.

Should also make clear this feature request is closed with prejudice -- modification of Property to support making multiple statements this way adds needless complexity.
