### ISSUE TITLE
Archive stale branches

### ISSUE THREAD

**Issue by gsarma** [openworm/PyOpenWorm#127]
@travs and I were discussing policies for deleting / archiving branches that have been merged and are no longer part of active development.  Tagging and archiving seems like a good way to go here.  See this SO post:

http://stackoverflow.com/questions/1307114/how-can-i-archive-git-branches

**Comment by slarson** [comment]
Good point.  I've gone ahead and thrown out a bunch that are obviously stale / transitory.  I've created a few pull requests for branches that seem like they may have useful stuff and asked about them.

**Comment by slarson** [comment]
i think that's the last of them
