### ISSUE TITLE
Doctest errors don't fail the build

### ISSUE THREAD

**Issue by slarson** [openworm/PyOpenWorm#144]
There are doctest errors right now but the build doesn't fail as a result of them.  I've left a trivial error in (some inconsistent leading whitespace in the README.md around line 197) and as you can see from [this build](https://travis-ci.org/openworm/PyOpenWorm/builds/66863639) it still passes.  

cc: @gsarma @travs

**Comment by travs** [comment]
Right, and there is also an error in ConfigureTest that doesn't fail the build. Checking into this now.

**Comment by slarson** [comment]
I got the ConfigureTest one in my latest commit :)
ᐧ

**Comment by slarson** [comment]
Closed by #145
