### ISSUE TITLE
Release latest master to PyPI

### ISSUE THREAD

**Issue by slarson** [openworm/PyOpenWorm#151]
This involves: 

- [x] Update badges in README.md to point to master instead of alpha0.5 branch
- [x] Do a [github release](https://help.github.com/articles/creating-releases/)
- [x] Follow [these instructions](https://wiki.python.org/moin/CheeseShopTutorial#Submitting_Packages_to_the_Package_Index) to submit

**Comment by travs** [comment]
We also need to update [these](https://github.com/openworm/PyOpenWorm/blob/15225aae39b2003ddf0ad1ddf10a8cd9d663167f/PyOpenWorm/__init__.py#L59) [two](https://github.com/openworm/PyOpenWorm/blob/15225aae39b2003ddf0ad1ddf10a8cd9d663167f/setup.py#L53) version variables as well, with whichever number we decide to adopt.

**Comment by slarson** [comment]
Done!
