### ISSUE TITLE
Single page explaining origin/history of CElegansNeuronTables.xls & NeuronConnectFormatted.xlsx, which one we will use & why...

### ISSUE THREAD

**Issue by pgleeson** [openworm/PyOpenWorm#152]
These spreadsheets contain essential information on the "connectome" we use but seem to have conflicting information and there are possibly multiple different versions.

Somewhere there needs to be a record of where they come from, which one will be used and how discrepancies are handled. This is related to a number of other issues:

https://github.com/openworm/PyOpenWorm/issues/10 (data sources)
https://github.com/openworm/CElegansNeuroML/issues/28 (which to use in c302)
https://github.com/openworm/CElegansNeuroML/issues/27 (update c302)
https://github.com/openworm/CElegansNeuroML/pull/23 (pull request comparing xsl files)

**Comment by travs** [comment]
@pgleeson 

Right. And there is also [NeuronConnect.xls being used in PyOpenWorm](https://github.com/openworm/PyOpenWorm/blob/5cc3042b004f167dbf18acc119474ea48b47810d/OpenWormData/scripts/insert_worm.py#L240) (though judging by the file changes in [this commit](https://github.com/openworm/CElegansNeuroML/commit/9c3627f45c49d583975f916c7bb5e80a1ad420ef?diff=unified) they may have the same contents; I'm not sure).

We can begin constructing the document @pgleeson and @slarson [outline here](https://github.com/openworm/PyOpenWorm/issues/10#issuecomment-46922081).

As for handling the discrepancies between these data sources, we can detail them in the same document, but how will we actually handle them? I will begin the list of sources so we will be able to judge their relative authority, but this is something we will need to discuss.

**Comment by ahrasheed** [comment]
@travs [NeuronConnectFormatted.xlsx](https://github.com/openworm/CElegansNeuroML/blob/master/NeuronConnectFormatted.xlsx) in CElegansNeuroML and NeuronConnect.xls which has been taken from [here](http://www.wormatlas.org/images/NeuronConnect.xls) are the same files. The only difference is that the names of some neurons have been changed to match those in [CElegansNeuronTables.xls](https://github.com/openworm/CElegansNeuroML/blob/master/CElegansNeuronTables.xls) by removing an extra zero in them (e.g. VA01 has been made VA1) so that c302 can use them correctly to generate .nml files. 

The commit you are referring to adds a comparison script to compare NeuronConnectFormatted.xls and [CElegansNeuronTables.xls](https://github.com/openworm/CElegansNeuroML/blob/master/CElegansNeuronTables.xls) (which is the primary data source in c302) and write an error log. A similar comparison is also done in the [pull request](https://github.com/openworm/CElegansNeuroML/pull/23) mentioned by @pgleeson.

**Comment by travs** [comment]
@ahrasheed thank you for the information. This discrepancy (zeros in the neuron names) also caused us problems, so we had to [normalize the names on insertion](https://github.com/openworm/PyOpenWorm/blob/master/OpenWormData/scripts/insert_worm.py#L220-L230) into the database. As long as we know these two sources are the same, we are now only dealing with two data sources ([CElegansNeuronTables.xls](https://github.com/openworm/CElegansNeuroML/blob/master/CElegansNeuronTables.xls) and NeuronConnect.xls).

The [work done by](https://github.com/openworm/CElegansNeuroML/pull/23) @aribrich and the logging script mentioned by @ahrasheed are informative for deciding which source to go with/how to handle discrepancies.

@pgleeson @slarson 
We should decide what to do about these differing data sources and begin to incorporate our decision into PyOpenWorm.

**Comment by slarson** [comment]
Most of the history of CElegansNeuronTables.xls is described [in this post](https://groups.google.com/d/topic/openworm-discuss/G9wKoR8N-l0/discussion) on the forum.  NeuronConnect.xls should be the authoritative reference going forward as it is published on a reference website (i.e. hasn't been processed by us).  This should be the case with work done by @ahrasheed and @aribrich .  Let's get a draft of this write up in MD in proper documentation format.

**Comment by travs** [comment]
@slarson 

I started something [here](https://github.com/openworm/PyOpenWorm/commit/6db3a5babf4b405e0068784ac448dcdd7e3a3a8b), but I can't access the docs project on ReadTheDocs to add the `dev` branch.

**Comment by pgleeson** [comment]
I agree that NeuronConnect.xls should be the authoritative reference (it would be good too to make a test to check that PyOpenWorm's copy is identical one downloaded from WormAtlas, in case it gets updated). The steps along the way from there to CElegansNeuronTables.xls should be documented, and ideally encoded in evidence() calls in PyOpenWorm. When it's all there PyOpenWorm should match the data generated from CElegansNeuronTables.xls in [SpreadsheetDataReader.py](https://github.com/openworm/CElegansNeuroML/blob/master/CElegans/pythonScripts/SpreadsheetDataReader.py). 

Sorry I can't be of more help with this data checking process, but it's pretty crucial for the integrity of data in PyOpenWorm.

**Comment by slarson** [comment]
HI @aribrich @pgleeson @travs @ahrasheed -- I've amended @travs good start on this page here:

https://github.com/openworm/PyOpenWorm/blob/dev/docs/data_sources.rst

My proposal is that we consolidate all .xls or .csv into the aux_data folder under PyOpenWorm.   This means the following spreadsheet files in other places should go away:

* CElegansNeuronTables.xls
* NeuronConnectFormatted.xlsx

This page should close issue #10 as well.

**Comment by travs** [comment]
With the advent and revision of [the data sources file](https://github.com/openworm/PyOpenWorm/blob/9378083b4f6d27076c7fad488eef6355341b8a3f/docs/data_sources.rst) this seems safe to close.

Please reply/reopen if you disagree with this one being closed.

**Comment by pgleeson** [comment]
Sorry, think there's more to go on this... That data description page should be bulletproof from a scientific perspective, it should be as detailed as would be required for a publication, citing in it the original references, discussing the labs involved, saying why these choices were made, etc.

Again, sorry to be annoying about this, but PyOpenWorm is going to form the basis for a lot of OpenWorm work and many routes for how we justify the parameters that go into the model will lead back to this page. It should be detailed enough to convince any c. elegans physiologist that we know the state of art in the field and have made informed choices.

**Comment by travs** [comment]
@pgleeson Good points you're raising here. I know I said to reopen this but I think it is fitting to open a separate issue as it is more general than just the connectome data source. #177 is opened in this regard, and is surely missing some of the relevant details. 
Padraig, if you're able to give that list a scan it would be greatly appreciated.
