### ISSUE TITLE
Create an Evidence coverage test

### ISSUE THREAD

**Issue by slarson** [openworm/PyOpenWorm#158]
Create a unit test under DataIntegrityTests that walks through all the facts in the DB, looks up what evidence supports it, and finds at least some evidence for every fact.

There are some starts to doing this in the comments on #75

**Comment by travs** [comment]
@gsarma We can discuss this tomorrow!

**Comment by gsarma** [comment]
@travs and I were wondering if this should be in DataIntegrityTest or EvidenceTest.  We made a dummy commit in EvidenceTest for now.

**Comment by gsarma** [comment]
@travs and I are working on this, but it seems that when you iterate over the generator neurons, the return type is a unicode string with the name of the neuron and not a neuron object: 

for n in neurons:
    n.type()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-60-2bf6c3e6e4c2> in <module>()
      1 for n in neurons:
----> 2     n.type()

AttributeError: 'unicode' object has no attribute 'type'

Is this as designed?

**Comment by slarson** [comment]
This could be improved, but at the moment, that is the [behavior in the api](https://pyopenworm.readthedocs.org/en/latest/_modules/PyOpenWorm/network.html#Network.neurons).  Superior behavior would be to return the objects instead of strings as now, but to make sure to implement [`__str__`, `__repr__` and maybe even `unicode`](http://stackoverflow.com/a/1535336/2733572) to ensure that the user can see a meaningful representation of the object when it is inspected interactively or printed out.

**Comment by travs** [comment]
@slarson 

We have three tests for this (muscles, neurons, connections) and a stub test for Channels over [here](https://github.com/openworm/PyOpenWorm/blob/0ca647a399c85b51e3f400f4ce5b1b718ace0c50/tests/EvidenceTest.py#L155-L191), but given the lack of tagged Evidence for each DataObject (#75), they are marked as expectedFailures.

Marking this as closed now.

**Comment by slarson** [comment]
Woo hoo!
ᐧ
