### ISSUE TITLE
Create an Evidence quality test

### ISSUE THREAD

**Issue by slarson** [openworm/PyOpenWorm#159]
Create a unit test under DataIntegrityTests that checks all evidence in the DB and ensures that it is filled out to a minimum standard of quality (i.e. there is at least a title, there is at least some kind of link to the material)

**Comment by travs** [comment]
@gsarma and I were discussing this and there are a few things we can be checking for in such a test:

- [ ] link (as Stephen mentioned) on every piece of evidence
- [ ] make sure the link resolves to something other than a 404 error

**Comment by gsarma** [comment]
@travs and I wrote tests for this.  They are marked expected failures for now, but otherwise, we can close this issue.
