### ISSUE TITLE
Continue breakdown of test.py

### ISSUE THREAD

**Issue by gsarma** [openworm/PyOpenWorm#161]
@travs and I previously broke out many of the tests in test.py into their own suites.  There are a few tests remaining that we left alone because they had slightly more complicated dependencies.  We want to make standalone test suites for the remainder of these tests so that test.py is simply a loader file- we should probably rename it TestLoader.py or POWTestLoader.py.

**Comment by travs** [comment]
@gsarma 
I know the install wasn't going easy on you yesterday; did you get any time to work on this one?

**Comment by gsarma** [comment]
With @travs:
Fixed by #173
