### ISSUE TITLE
Create DataIntegrityTest to address synaptic connections

### ISSUE THREAD

**Issue by travs** [openworm/PyOpenWorm#163]
Given the data source, this test should verify that:
- [x] the number of connections matches
- [x] the contents of each connection matches
- [x] the number of unique neurons making these connections matches

Raised from [points made by](https://github.com/openworm/CElegansNeuroML/issues/27#issuecomment-114135436) @ahrasheed

**Comment by slarson** [comment]
In addition, do have a look at @aribrich 's work on openworm/CElegansNeuroML#23 .  I suspect there will be some code here to reuse!

**Comment by travs** [comment]
Discussions evolving over in openworm/CElegansNeuroML#27 highlight the importance of this issue. 
We can reuse some code from https://github.com/openworm/CElegansNeuroML/pull/46 as well.

**Comment by travs** [comment]
@ahrasheed has identified that this issue is a roadblock to completing https://github.com/openworm/CElegansNeuroML/issues/28, and perhaps some related issues in c302. 

Abdullah, would you feel comfortable looking at this issue as well? I would like to get this one resolved myself, but it seems like you have a large start on this in [the comments/script you adapted](https://github.com/openworm/CElegansNeuroML/issues/27#issuecomment-114135436), and I don't want to copy/paste your own code into another repo. Let me know what you think, and I'll have a look at the other roadblock (#162) in the meantime.

**Comment by ahrasheed** [comment]
@travs Sure, this seems to be just an issue of adding the connections again. Since the number of connections is less than that in NeuronConnect.xls (which is the source for PyOpenWorm). And once that is resolved it should be trivial to add more tests [here](https://github.com/openworm/PyOpenWorm/blob/master/tests/DataIntegrityTest.py#L88-L93). It will be slow until #162 is resolved, but will still work.

**Comment by travs** [comment]
To reiterate from the gitter chat, this issue depends on getting the new connectome in place first (https://github.com/openworm/PyOpenWorm/issues/168).

**Comment by ahrasheed** [comment]
@slarson @travs @signija 

Please check the update to #168 

Using the new connectome following connection numbers apply for creating data integrity tests:

- Total number of neurons: **302**
- Total number of muscles: **144**
- Total number of neuron to neuron connections: **5805**
- Total number of neuron to muscle connections: **1111**
- Total number of unique neurons making connections in the new connectome: **300**
- Two unconnected neurons: **CANL** and **CANR**

All of these facts should be translated into tests.

**Comment by slarson** [comment]
My understanding is that this is completed and we just need to complete #265 to fix final bugs and integrate it into the dev branch.

**Comment by mwatts15** [comment]
@signija Are you still the primary on this ticket? Is this one awaiting review? All of the tests listed by @ahrasheed are in DataIntegrityTests, although:
```
Total number of muscles: 144 
```
Doesn't match. The number of muscles is compared against 158 since aa8ebdf064ea.

**Comment by signija** [comment]
I've lost track of this issue. Where are we standing on this right now? @mwatts15 @slarson

**Comment by mwatts15** [comment]
@signija all of the data is there, and the tests are passing, so I'm closing this one.
Thanks everyone for your work on this.
