### ISSUE TITLE
Port connectome comparison script from c302

### ISSUE THREAD

**Issue by travs** [openworm/PyOpenWorm#164]
Bring the script by @aribrich in https://github.com/openworm/CElegansNeuroML/pull/23 over to this repo and make sure we can run it in this repo.

Will be useful to compare two data sources when justifying which one we are using.

@aribrich

**Comment by pgleeson** [comment]
This is certainly the best place for the comparison scripts.

**Comment by travs** [comment]
@aribrich

Hey Ari, what's the status of this one?

**Comment by travs** [comment]
@aribrich Just to close the loop on the chat we had, I can go ahead and move the script over here. I can also definitely make sure your name and handle are in the comments as the author of the script. What do you think?

**Comment by aribrich** [comment]
@travs , if you have the time, please go ahead a move the script. I haven't had a minute to look at this in the last few weeks, so it might be the best way to close this issue. Don't worry about the handle - I just had that in there when I was working on my machine.

**Comment by travs** [comment]
@slarson Given the advent of the new connectome, is there any reason to port this over here? We would also have to port over `CElegansNeuronTables.xls` and `NeuronConnectFormatted.xlsx`.

**Comment by travs** [comment]
Given the amount of tests that grew out of the connectome comparison by @aribrich, we have a lot of coverage for the network in PyOpenWorm. 

We are moving to a new connectome, so we can leave that script outside PyOpenWorm, since it deals with the connectome versions we are actually moving away from.
