### ISSUE TITLE
Create a cleaner installation experience

### ISSUE THREAD

**Issue by gsarma** [openworm/PyOpenWorm#169]
Discussion with @travs:
1) Installation (for all OpenWorm modules) shouldn't be verbose by default
2) Log files should be optionally generated for debugging issues that arise

**Comment by slarson** [comment]
Thanks for raising it.  What would we do to make [the install procedure](https://github.com/openworm/PyOpenWorm/blob/master/INSTALL.md) less verbose?  It is down to one line if you have pip and 3 if you don't.

**Comment by gsarma** [comment]
Ah sorry- we were referring to the output to the terminal during the installation.  Of course, it would be great if pip itself supported this (maybe it does?), but if not, it would be nice to have a wrapper script that suppressed the output and simply displayed a status update as the installation progressed.

**Comment by cheelee** [comment]
@gsarma I think we should always generate an installation log file as a default, whilst keeping installation output to just "success/warning/failure" notices. The rationale behind suggesting such a  default is because I don't think we should be asking users to run installation a second time (which may or may not suffer from additional side-effects) just so they can debug what went wrong the first time around.

**Comment by travs** [comment]
I believe pip does have a verbose option that can be enabled/disabled.

Maybe we would have to suppress the output or redirect it into a different stream that can only display to terminal when `-v` is enabled.

**Comment by mwatts15** [comment]
Closing this as invalid. I can't control what a user sees on their terminal and, in general, I don't want to. For users that don't care about the output, they'll ignore it whether there's a lot or a little. For those that do care, every shell I know has redirection to a file.
I would support having a log file, if possible, result from the install procedure for bug reporting purposes. I suspect that will be up to the installation method, but we could document how best to collect the record.
