### ISSUE TITLE
Write descriptions for each test file of type _DataTest

### ISSUE THREAD

**Issue by gsarma** [openworm/PyOpenWorm#171]
@travs and I finished breaking down test.py so that each class is in it's own file.  Many of these (the ones of type _DataTest) need high-level descriptions.  This should be easy- the individual tests in each class already have descriptions, we just need an overall description for someone quickly scanning test.py.  The description should justify why these tests were included as a single module.

**Comment by gsarma** [comment]
I've added a few descriptions by looking at the comments to the tests themselves, but there are a number of them that I don't really understand well enough to write descriptions for:
https://github.com/gsarma/PyOpenWorm/commit/924b65e7d6438f200f7d5f2141cb97ee29c7a789

Also, many of the tests are still missing descriptions.  

@slarson can you finish this by looking through the comments marked TODO in test.py?  Thank you!

**Comment by mwatts15** [comment]
Added comments for a couple of test files that weren't named for the class under test. Generally, naming test classes like '<ClassUnderTest>Test' should be sufficient.
