### ISSUE TITLE
Create test and fix: Generators reset when called

### ISSUE THREAD

**Issue by gsarma** [openworm/PyOpenWorm#175]
@travs and I are both seeing this issue:

```
import PyOpenWorm as P
P.connect()
net = P.Worm().neuron_network()
neurons = net.neurons()
In [78]: len(list(neurons))
Out[78]: 302
In [79]: len(list(neurons))
Out[79]: 0
```

**Comment by slarson** [comment]
Good catch @gsarma and @travs -- let's definite do a test that captures this, in addition to figuring out what is going on.

**Comment by gsarma** [comment]
@travs and I added a test for this.  Still investigating the original problem.

**Comment by mwatts15** [comment]
The test for this was broken at the latest revision -- I corrected it and found it's passing. The properties had been returning generators from __call__ . Wrapping the results in a set() resolves the issue and has been resolved.
