### ISSUE TITLE
Fill in details on all citations in datasource description page

### ISSUE THREAD

**Issue by travs** [openworm/PyOpenWorm#177]
Raised from [Padraig's point here](https://github.com/openworm/PyOpenWorm/issues/152#issuecomment-118400726).

We need to make [the datasource description page](https://github.com/openworm/PyOpenWorm/blob/dev/docs/data_sources.rst) more rigorous, adding things like:

- [x] citations of original references
- [x] discussion of labs involved
- [x] explanation of decisions we made about the datasources
- [x] Add in citation for the new connectome spreadsheet being integrated

@pgleeson Please edit this post or comment with additional specs for what should be included in this page other than what I have listed.

**Comment by pgleeson** [comment]
Looks good so far...

Btw, I thought the documentation had been translated to markdown at some stage..?

**Comment by travs** [comment]
@pgleeson In some other repos it has, but not here because of the heavy usage of docstrings/autodocs. When `Mkdocs` supports this (specifically, the version that RTD is using), we can switch over easily.

**Comment by slarson** [comment]
@pgleeson Check out [the latest](https://github.com/openworm/PyOpenWorm/blob/634743d9cf2990b748f9a94af82aab34fa1699f4/docs/data_sources.rst).  I've fleshed it out considerably.  I don't know what kind of standard you are looking for in terms of "discussion of labs involved".  Could you give an example in the context of what's there now?

**Comment by pgleeson** [comment]
@slarson That's certainly more like what's needed. It would be great to:

- [ ] get this page on (or at least more visible on) the main docs site, e.g. prominently on http://docs.openworm.org/en/0.9/Projects/datarep/
- [ ] link to this from the page for scientists:  http://www.openworm.org/science.html

See https://github.com/openworm/CElegansNeuroML/issues/49 for discussion on using the new connectome in c302 etc.

**Comment by slarson** [comment]
OK, great!  Closing this one for now.  Those suggestions have been moved into issues on their own repos over here:

https://github.com/openworm/org.openworm.website/issues/60 https://github.com/openworm/openworm_docs/issues/37
