### ISSUE TITLE
Remove expectedFailures from EvidenceTests

### ISSUE THREAD

**Issue by travs** [openworm/PyOpenWorm#180]
@gsarma and I went through and made three new tests that check that each DataObject has evidence attached to it.

Once we have evidence we can remove the expectedFailure decorators from these tests.

Raised from #158. Depends on #75 and related issues.

**Comment by mwatts15** [comment]
Estimate of three using the same logic as for #183

**Comment by mwatts15** [comment]
There are no expectedFailures on EvidenceTest at this point.
