### ISSUE TITLE
Ensure appropriate granularity of tests

### ISSUE THREAD

**Issue by gsarma** [openworm/PyOpenWorm#184]
Discussion with @travs:
In some cases, we have a single test that verifies an entire class of behavior.  For example, in the evidence quality tests that we just added, we verify wholesale that every fact has a doi or url.  This means that in the event that there is a failure, the user will have to interactively determine where exactly the failure is- the test won't reveal that information. 

We should review all of the tests at some point and make sure they are appropriately granular for the sake of making debugging easier.  One way to do this would be to use generating tests:

http://nose.readthedocs.org/en/latest/writing_tests.html#test-generators
- [x] Provide adequate reporting of the cause for failures in reporting of DOI / URL presence in Evidence
- [ ] *Others?*

**Comment by mwatts15** [comment]
This task needs to be broken down into a list of which tests need to be decomposed and how.

**Comment by mwatts15** [comment]
It's hard to do this as one self-contained task. Developers should keep in mind how to write good tests that explain themselves, but that's ongoing.
