### ISSUE TITLE
Write test for WormBaseID coverage

### ISSUE THREAD

**Issue by travs** [openworm/PyOpenWorm#187]
All of these should have a wormbaseID:

- [x] cells
- [x] muscles
- [x] neurons

Also note to write a docstring for this new part of the schema.

**Comment by slarson** [comment]
@signija check this out.

**Comment by slarson** [comment]
Great job on #200!!  Next step on this is to add to [DataIntegrityTest.py](https://github.com/openworm/PyOpenWorm/blob/dev/tests/DataIntegrityTest.py)  a check that pulls all cells, neurons, and muscles, and ensures that the Wormbase ID is actually populated.  @travs is working on adding this data now, so for now, the goal is to add this test with a [unittest.expectedFailure decorator](https://docs.python.org/2/library/unittest.html#unittest.expectedFailure).  Then when it is populated, we'll take off the decorator.

**Comment by travs** [comment]
Closed by #214
