### ISSUE TITLE
Restore ability to run tests individually

### ISSUE THREAD

**Issue by gsarma** [openworm/PyOpenWorm#190]
With @travs:
As the testing suite has been broken down and modularized, we've lost the ability to run tests individually.  For example:
```
python tests/test.py DataIntegrityTest
```
and so on will return:

```
Testing with configs: ['tests/test_default.conf', 'tests/test_ZODB.conf']

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
```

We need to restore this functionality.

**Comment by gsarma** [comment]
Fixed by:
https://github.com/gsarma/PyOpenWorm/commit/030c59e8030d54bf188adaf9e25c72939ab63a6d

**Comment by travs** [comment]
:+1: :+1: :+1:
