### ISSUE TITLE
Investigate benefits of using Nose for testing

### ISSUE THREAD

**Issue by gsarma** [openworm/PyOpenWorm#192]
With @travs:
General discussion about merits of moving to Nose.  @cheelee do you have any thoughts? 

Possible options:
1) Migrate existing code base over to Nose (might not be worth the investment).  
2) Move to Nose for new tests

Relevant issues:
#190- moving to Nose might make it easier to run tests individually.  
See also #184.

**Comment by cheelee** [comment]
I'm not familiar with Nose, but I'll check it out. Adding a quick link to give some context for others if they are interested:

http://pythontesting.net/framework/nose/nose-introduction/

**Comment by travs** [comment]
With @gsarma:
It seems more reasonable to adopt nose going forward, and have backward-compatibility to allow us to write new tests in nose (reaping whatever benefits Nose may give), but not break our old testing scheme.

**Comment by gsarma** [comment]
@travs and I are looking into using coveralls for tracking test coverage.  It looks tricky to actually get working, and this person suggests that using nose helps the process:

http://levibostian.com/python-code-coverage-and-coveralls-io/

**Comment by gsarma** [comment]
Also relevant:

https://sourcegraph.com

**Comment by travs** [comment]
@kevcmk has commented on difficulties in configuring Nose, and offers that py.test may be a better option. I just suggested Nose as it's what I've used in the past, but anything that is more developer-friendly is good by me

**Comment by slarson** [comment]
Based on @kevcmk's [analysis](https://gitter.im/openworm/PyOpenWorm?at=55adfb63ea4b0b3b25a501c8), I'd suggest we close this and move ahead with PyTest.  Cool?

**Comment by gsarma** [comment]
I'm fine with closing it.  I've been reading a blog on Python unit testing, and he says some contradictory things about PyTest versus nose.  I'll keep learning about both and it doesn't seem like we will be closing off options for ourself in any case for the future.
