### ISSUE TITLE
Fix Connection object generation with strings

### ISSUE THREAD

**Issue by travs** [openworm/PyOpenWorm#199]
Currently if a pre_cell or post_cell are specified with a string when making a Connection object, they will be assumed to be Neurons. The code for this is [here](https://github.com/openworm/PyOpenWorm/blob/dev/PyOpenWorm/connection.py#L52-L66).

Since Connections can now be between Neurons and Muscles, this should be updated.

Will require looking at the list of Muscles and list of Neurons to find which type the string is assuming. Problem is, this is too slow now, so #162 must be solved first.

**Comment by mwatts15** [comment]
Now that `Connection` can describe relationships between non-neurons, it's better to deprecate passing bare strings and instead encourage to use `Cell`. I've introduced a deprecation warning with plans to remove in the next release.
