### ISSUE TITLE
Rename PyOpenWorm folder to openworm

### ISSUE THREAD

**Issue by pgleeson** [openworm/PyOpenWorm#2]
For a more pythonic:

    import openworm
    net = openworm.Network()

**Comment by travs** [comment]
@pgleeson Do you still feel strongly about this, or can we close it?

**Comment by pgleeson** [comment]
Arguably more Pythonic, but at this stage "PyOpenWorm" is pretty established as the brand name for this and I suppose it's not a big issue to keep it as is.
