### ISSUE TITLE
Facts cannot be asserted by multiple distinct Evidence objects

### ISSUE THREAD

**Issue by travs** [openworm/PyOpenWorm#211]
As the API works right now, we can't use distinct Evidence objects to assert the same fact. 
The first Evidence object is overwritten it seems.

Some interactive output:

``` python
import PyOpenWorm as P
P.connect()
e1 = P.Evidence()
e1.pmid('777')

e2 = P.Evidence()
e2.pmid('888')

c = P.Channel()
e1.asserts(c.description)

evs = P.Evidence()
e2.asserts(c.description)

e1.save()
e2.save()
evs.asserts(c.description)

print([x.pmid() for x in evs.load()])
#[u'888', u'888']
# expected: [u'777', u'888']
```

We can close this issue when we have a fix for this which gives the expected behaviour. 
#212  is for a test that catches this.

**Comment by mwatts15** [comment]
Evidence needs to override the identifier method of `DataObject` to base its identifier on the PMID in order for this to work.

**Comment by travs** [comment]
@mwatts15 Ok, and can we base an identifier on multiple properties? I think we would need to have similar functionality leading to the expected output for many properties of Evidence (`doi`, `pmid`, `wormbaseid` and `uri`, potentially).

**Comment by mwatts15** [comment]
@slarson added tests based on the one you created for the other types of id.
