### ISSUE TITLE
Travis-CI Test Build #447 introduced atexit._run_exitfuncs errors

### ISSUE THREAD

**Issue by cheelee** [openworm/PyOpenWorm#215]
I just noticed starting from Build #447 (https://travis-ci.org/openworm/PyOpenWorm/builds/70450878), we've had every test's atexit call fail as follows:

Error in atexit._run_exitfuncs:

Traceback (most recent call last):

  File "/opt/python/2.7.9/lib/python2.7/atexit.py", line 24, in _run_exitfuncs

    func(*targs, **kargs)

  File "./PyOpenWorm/__init__.py", line 114, in disconnect

    if not m.connected:

AttributeError: 'module' object has no attribute 'connected'

**Comment by travs** [comment]
You're right, this output doesn't seem to affect the passing/failing of tests but something weird is definitely going on. Good catch @cheelee

**Comment by travs** [comment]
@kevcmk's #216 seems to fix this (or at least not flood the output with this text). If we can get the test numbers to match up we could potentially close this one.

**Comment by cheelee** [comment]
Yah, agreed.

**Comment by cheelee** [comment]
The test numbers match up. py.test is correct and our old test.py ended up generating 77 duplicate tests, whilst missing 12 tests that py.test caught. This is good. Thanks for the great feedback @travs and the awesome job using py.test @kevcmk . I'm closing this issue, and I think we can make that pull request merge official.

**Comment by travs** [comment]
@cheelee Awesome! Thanks for looking into this :)
