### ISSUE TITLE
Change as_networkx to pull from connectome.csv in this repo, not dataviz

### ISSUE THREAD

**Issue by travs** [openworm/PyOpenWorm#222]
Related:
#218 #221

**Comment by slarson** [comment]
See these files for where the path appears to be that needs changing:

https://github.com/openworm/PyOpenWorm/blob/15225aae39b2003ddf0ad1ddf10a8cd9d663167f/OpenWormData/scripts/default.conf
https://github.com/openworm/PyOpenWorm/blob/15225aae39b2003ddf0ad1ddf10a8cd9d663167f/PyOpenWorm/default.conf
https://github.com/openworm/PyOpenWorm/blob/15225aae39b2003ddf0ad1ddf10a8cd9d663167f/tests/test.conf
https://github.com/openworm/PyOpenWorm/blob/15225aae39b2003ddf0ad1ddf10a8cd9d663167f/tests/test_ZODB.conf
https://github.com/openworm/PyOpenWorm/blob/15225aae39b2003ddf0ad1ddf10a8cd9d663167f/tests/test_data/bad_test.conf

**Comment by travs** [comment]
Fixed by #223
