### ISSUE TITLE
Implement bibtex field for Evidence object

### ISSUE THREAD

**Issue by travs** [openworm/PyOpenWorm#245]
Not sure if we should have the parser built into the Evidence object, or if we should just be able to give the `Evidence.bibtex` field a string like we do for `Evidence.pmid`.

Looks like the beginnings of this are [here](https://github.com/openworm/PyOpenWorm/blob/15225aae39b2003ddf0ad1ddf10a8cd9d663167f/PyOpenWorm/evidence.py#L274-L275), but as it is now, this is what we get:

``` python
>>> e = P.Evidence()
>>> e = P.Evidence(bibtex='bib fortuna')
>>> e.bibtex

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Evidence' object has no attribute 'bibtex'

>>> e._fields

{'bibtex': 'bib fortuna'}
```

**Comment by mwatts15** [comment]
IIRC, conversation with @slarson concluded the bibtex argument was intended to be a source for the evidence i.e., you submit the content of a BibTeX entry as a string and then we fill in `Evidence` fields (e.g., author, title, year). So there wouldn't be a property 'Evidence.bibtex' to get Evidence from.

The syntax could be something like `Evidence.from_bibtex('@BOOK{strunk-and-white, author = ...')` to distinguish from the main initializer arguments.

**Comment by mwatts15** [comment]
This is done. Most of the fields on `Evidence` have been moved to `Document`. BibTeX is turned into a `Document` like this:
```
bibtex = u"""@ARTICLE{Cesar2013,
  author = {Jean César},
  title = {An amazing title},
  year = {2013},
  month = jan,
  volume = {12},
  pages = {12--23},
  journal = {Nice Journal},
  abstract = {This is an abstract. This line should be long enough to test
     multilines...},
  comments = {A comment},
  keywords = {keyword1, keyword2},
}
"""
assert u'Jean César' in Document(bibtex=bibtex).author()
```
or
```
from PyOpenWorm.bibtex import bibtex_to_document
doc = bibtex_to_document(bibtex)
```
and an `Evidence` is created from a `Document` like this:
```
Evidence(reference=doc)
```
