### ISSUE TITLE
Investigate opening multiple read connections to PyOpenWorm's database

### ISSUE THREAD

**Issue by travs** [openworm/PyOpenWorm#247]
Not sure offhand how to go about this, but it's important for https://github.com/joebowen/model_completion_dashboard/issues/7.

Using PyOpenWorm as the backend for the model completion dashboard would benefit from something like this.

@joebowen

**Comment by mwatts15** [comment]
It looks like what it would take is to define your own source. Based off of ZODBSource, you'd want something like this (untested):
```        
    def open(self):
        import ZODB
        from ZODB.ClientStorage import ClientStorage
        self.addr = self.conf['rdf.store_conf']
        storage = ClientStorage(self.addr)
        self.zdb = ZODB.DB(storage)
        self.conn = self.zdb.open()
        root = self.conn.root()
        if 'rdflib' not in root:
            root['rdflib'] = ConjunctiveGraph('ZODB')
        self.graph = root['rdflib']
        try:
            transaction.commit()
        except Exception:
            # catch commit exception and close db.
            # otherwise db would stay open and follow up tests
            # will detect the db in error state
            L.warning('Forced to abort transaction on ZODB store opening')
            traceback.print_exc()
            transaction.abort()
        transaction.begin()
        self.graph.open()
```

**Comment by mwatts15** [comment]
This must be tested out with multiple PyOpenWorm connections.

**Comment by mwatts15** [comment]
Closing this one as invalid: generally making PyOpenWorm thread-safe or standardizing how it is used in a given web server's request/response framework is too ill-specified in the first case and too implementation specific in the second. In lieu of a bug report or feature request on PyOpenWorm, there's nothing for us to do.
