### ISSUE TITLE
Make Network.as_networkx() pull from DB

### ISSUE THREAD

**Issue by slarson** [openworm/PyOpenWorm#253]
Right now, Network.as_networkx() is being initialized [directly out of a csv file](https://github.com/openworm/PyOpenWorm/blob/dev/PyOpenWorm/data.py#L344), which skips the entire DB.  Instead, we should make a networkx object by querying the DB and packaging it into a networkx object.

- [ ] Move the _init_networkx method out of PyOpenWorm/data.py into PyOpenWorm/network.py
- [ ] Add a query in `Network` on `Connection` to get all connections and create a networkx network.

**Comment by mwatts15** [comment]
This may be revisited with a networkX data translator
