### ISSUE TITLE
Problem installing PyOpenWorm on Windows

### ISSUE THREAD

**Issue by walkel3** [openworm/PyOpenWorm#263]
Using c:\python27\lib\site-packages\six-1.9.0-py2.7.egg
Finished processing dependencies for PyOpenWorm==0.5.3
Running post-install script(s)
Running insert_worm.py as UID 0
Traceback (most recent call last):
  File "post_install.py", line 23, in <module>
    pid = os.fork()
AttributeError: 'module' object has no attribute 'fork'

**Comment by mwatts15** [comment]
@travs You should probably have a look.

**Comment by slarson** [comment]
[This stackoverflow answer](https://stackoverflow.com/questions/17300551/how-to-run-python-script-with-os-fork-on-windows) provides a good perspective on what's going wrong here.

**Comment by mwatts15** [comment]
The reason for the `fork` isn't valid since the process doesn't have to be called asynchronously.

**Comment by mwatts15** [comment]
The setup.py no longer uses `os.fork`.
