### ISSUE TITLE
Make pip complain if you try to install with python3

### ISSUE THREAD

**Issue by slarson** [openworm/PyOpenWorm#270]
PyOpenWorm isnt python 3 compatible yet.  People installing with it won't know this and it will look broken

**Comment by MarcoDev200** [comment]
Full error message from my experience


Collecting wsgiref==0.1.2 (from pyopenworm)
  Downloading wsgiref-0.1.2.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "C:\Users\Marco\AppData\Local\Temp\pip-build-9xmj79iu\wsgiref\setup.py", line 5, in <module>
        import ez_setup
      File "C:\Users\Marco\AppData\Local\Temp\pip-build-9xmj79iu\wsgiref\ez_setup\__init__.py", line 170
        print "Setuptools version",version,"or greater has been installed."
                                 ^
    SyntaxError: Missing parentheses in call to 'print'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\Marco\AppData\Local\Temp\pip-build-9xmj79iu\wsgiref

**Comment by jni** [comment]
Why is wsgiref included at all? It appears to be part of the Python stdlib?

At any rate, sorry for the trolling, but I would hope that Python 3 support itself would be in the pipeline? I wanted to include a reference to PyOpenWorm in Elegant SciPy but we are writing it for Python 3 only...

**Comment by mwatts15** [comment]
@jni Just to track the history of interest in porting to python3, this was first mentioned more than a year ago in #66, but hasn't been updated since then.

**Comment by jni** [comment]
Ah, sorry, I had a quick scan of the issues before posting, but missed that one. And this one actually described the exact problem I'd come across before coming to this repo. =)

**Comment by jni** [comment]
If someone tells me why wsgiref is being pip-installed (rather than using the stdlib), I can try to take a stab at porting...

**Comment by mwatts15** [comment]
Python 3 is supported now.
