### ISSUE TITLE
Install problems (py2)

### ISSUE THREAD

**Issue by clbarnes** [openworm/PyOpenWorm#292]
Expected behaviour: In a clean python 2 environment with a clean pip cache etc., calling `pip install pyopenworm` should install pyopenworm without error.

Actual behaviour: All is fine until

```bash
Collecting FuXi (from pyopenworm)
  Downloading FuXi-1.0-rc.dev.tar.gz (95kB)
    100% |████████████████████████████████| 102kB 5.3MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-gwQrf1/FuXi/setup.py", line 1, in <module>
        import ez_setup
    ImportError: No module named ez_setup
```

Steps to reproduce behaviour: 

```bash
rm -r ~/.cache/pip/*  # clear the pip cache
conda create -n pyopenworm2 python=2.7  # create an empty conda environment
source activate pyopenworm2  # activate the conda environment
pip install pyopenworm
```

The clean conda environment has a `pip freeze` looking like this:

```
autopep8==1.2.1
backports.shutil-get-terminal-size==1.0.0
cycler==0.9.0
decorator==4.0.11
enum34==1.1.6
ipython==5.1.0
ipython-genutils==0.1.0
nose==1.3.7
path.py==8.1.2
pathlib2==2.2.0
pbr==1.8.1
pep8==1.6.2
pexpect==4.2.1
pickleshare==0.7.4
prompt-toolkit==1.0.9
ptyprocess==0.5.1
Pygments==2.1.3
pytz==2015.7
scandir==1.4
simplegeneric==0.8.1
six==1.10.0
stevedore==1.9.0
traitlets==4.3.1
virtualenv==13.1.2
virtualenv-clone==0.2.6
virtualenvwrapper==4.7.1
wcwidth==0.1.7
```

An issue which may or may not be related is that FuXi requires `rdflib < 3a` and the `setup.py` requires `rdflib==4.1.2`. This means that if rdflib is installed first, FuXi will overwrite it and things may work, but if rdflib is installed second, FuXi won't work.

**Comment by clbarnes** [comment]
By calling `pip install ez_setup`, I can avoid this error - so `ez_setup` should be added to the `setup.py` requirements.

However, I then get this one:

```
Processing dependencies for PyOpenWorm==0.6.0
    error: rdflib 4.1.2 is installed but rdflib<3a is required by set(['FuXi'])
    
    ----------------------------------------
Command "/home/cbarnes/anaconda3/envs/pow2_2/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-HhlbIo/pyopenworm/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-atJth_-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-HhlbIo/pyopenworm/
```

This issue is created by the fact that FuXi requires rdflib < 3a and the setup.py requires rdflib==4.1.2. This means that if rdflib is installed first, FuXi will overwrite it and things may work, but if rdflib is installed second, FuXi won't work.

**Comment by clbarnes** [comment]
I'm not well-versed in PyPI so I don't know how similar `pip install` and `setup.py install` are, but adding ez_setup helps.

However, yarom requires a modern version of rdflib and FuXi requires an ancient version of rdflib - there doesn't seem to be a way around that conflict.

```
error: rdflib 2.4.2 is installed but rdflib>=4.1.2 is required by set(['yarom'])
```

Is FuXi even maintained any more? The homepage link on PyPI is dead, the github repo claims to be obsolete and non-functioning, and points to a Google Code repo (google code having been retired a year ago), which is itself in archive state; and it's based on an rdflib 2 major versions ago. Is there another library which could be used instead?

**Comment by mwatts15** [comment]
There was work done to make FuXi compatible with RDFLib 4 rdflib/FuXi@4d245e9463ea59d76bba81ecabfe1e7b056ceaee4. Looking over a recent large changeset on FuXi, I see issues with code quality, like commented-out code, needless repetition in imports, broken links to supporting references, changes *away* from PEP8, removal of `__all__` lists (suggesting higher coupling), and less explicit messages in exceptions that give me some pause.

There doesn't seem to be a viable alternative that's intentionally rdflib compatible and which is better maintained. Given the small scope of reasoning with N3 in PyOpenWorm, I'm more inclined to remove reasoning as a feature. There's still a path for those that want it to build and apply their own rules with FuXi or another reasoner, but I'm going to deprecate then remove the usages of FuXi in PyOpenWorm now.
