### ISSUE TITLE
Error from 'aneuron' on PyPi version of pyopenworm

### ISSUE THREAD

**Issue by slarson** [openworm/PyOpenWorm#301]
I installed PyOpenWorm using " pip install pyopenworm " 
and then ran the following commands 

>>> import PyOpenWorm as P 
>>> P.connect() 
>>> net = P.Worm().get_neuron_network() 
>>> 
>>> aval = net.aneuron('AVAL') 
Traceback (most recent call last): 
  File "<stdin>", line 1, in <module> 
AttributeError: 'NoneType' object has no attribute 'aneuron' 

Any response would be appreciated. 

Thanks, 
Shubham

**Comment by lungd** [comment]
I could reproduce this issue with a new virtualenv.

Please try to install PyOpenWorm with 'python setup.py install' from inside the root directory after cloning the repo.
If you install PyOpenWorm with setup.py the post_install.py file gets executed and I think this step is missing from the pip installation.

**Comment by shubhsingh594** [comment]
@lungd  yeah it works if I install using 'python setup.py install ' . 
Thanks :)

**Comment by slarson** [comment]
This means there is a problem with the PyPi deployment.  We'll have to address this soon / on next release.

**Comment by mwatts15** [comment]
Thanks for reporting @shubhsingh594. I'm looking at the pip install procedure now.

**Comment by mwatts15** [comment]
This bug is for an earlier version of PyOpenWorm. Currently, the behavior described in the description is expected when you don't have anything in the database, which might be the case on initial install if you never created a PyOpenWorm database.
