### ISSUE TITLE
Verify that test.py only imports tests externally, then revise documentation to reflect that

### ISSUE THREAD

**Issue by gsarma** [openworm/PyOpenWorm#327]
The [Readme](https://github.com/openworm/PyOpenWorm/tree/master/tests) for the testing suite states that test.py contains many tests and also imports tests from other files.  It should only do the latter.  If not, these tests should be separated out, and then the documentation needs to be updated.

**Comment by mwatts15** [comment]
Since we switched to py.test, test.py is defunct -- just been hanging around.

**Comment by gsarma** [comment]
Got it- thanks for the update.  I'll catch up on the changes over the next few months.

**Comment by mwatts15** [comment]
@gsarma Please have a look at `dev`for the latest. I try to keep that all working :)
