### ISSUE TITLE
Archive stale branches (10/2017)

### ISSUE THREAD

**Issue by gsarma** [openworm/PyOpenWorm#328]
Whenever the time is right!  

http://stackoverflow.com/questions/1307114/how-can-i-archive-git-branches

**Comment by mwatts15** [comment]
Old branches should be deleted if there's no useful work on them which hasn't been merged. I've removed the branches had no commits ahead of master and the remainder still have pending work.

**Comment by gsarma** [comment]
Thanks for taking care of this!
