### ISSUE TITLE
Fix code coverage reporting pipeline

### ISSUE THREAD

**Issue by gsarma** [openworm/PyOpenWorm#331]
Coveralls is failing for recent builds.

Many people seem to have had this issue:
https://github.com/lemurheavy/coveralls-public/issues/281

**Comment by mwatts15** [comment]
It is currently working. It wasn't coveralls fault though: the build was only set to run on success and the build had been failing for some time. Changed the policy to always run unless there's an error. Also, we hadn't been installing coveralls before the build? Not quite sure why it ran before.
