### ISSUE TITLE
Clarify relationship between PyOpenWorm and ChannelWorm in Documentation

### ISSUE THREAD

**Issue by gsarma** [openworm/PyOpenWorm#338]
For newcomers, and even people who have some experience with the project, it's not entirely clear what the relationship is between PyOpenWorm and ChannelWorm.  I realize that this is largely historical and pragmatic at this point, but we really need to make it clear exactly what's going on here.  If anyone has thoughts about this, please message me.

**Comment by gsarma** [comment]
#341

**Comment by mwatts15** [comment]
I think the changes to the README are sufficient to draw the distinction, so closing now.
