### ISSUE TITLE
 "beginner": py.test failed , .pow/worm.db.lock not found . install problem for help

### ISSUE THREAD

**Issue by porridgeshoes** [openworm/PyOpenWorm#370]
### Hi,
could i ask a fool question about installation?
my install step is:
1. run pip install  PyOpenWorm in ubuntu system, it shows install successfully.
2. And then  download PyOpenWorm from github , and  run py.test in root fold , but test failed.
I know it must be something wrong in my install step ,but i dont know how to fix it, please help me ,thank you!!

it  like:
yan@S400:~/PyOpenWorm$ py.test
============================= test session starts ==============================
platform linux -- Python 3.6.1, pytest-3.0.7, py-1.4.33, pluggy-0.4.0
rootdir: /home/yan/PyOpenWorm, inifile: pytest.ini
collected 264 items 

tests/BibtexTest.py ........
tests/CLITest.py ........
tests/CellTest.py ..........
tests/ChannelTest.py .......
tests/CommandTest.py .................................
tests/ConfigureTest.py ...................
tests/ConnectionTest.py .....
tests/ContextTest.py ........................
tests/DataIntegrityTest.py FFFFFFFssFFFFFFFFFFFs
tests/DataObjectTest.py ..........ss
tests/DataUserTest.py .s.x..
tests/DatabaseBackendTest.py s.....
tests/DatasourceTest.py ......................
tests/DocumentTest.py ..FF...
tests/DocumentationTest.py F
tests/EvidenceCoverageTest.py sFFF
tests/EvidenceQualityTest.py F
tests/EvidenceTest.py ....
tests/ExampleRunnerTest.py .FFsFFF
tests/ExperimentTest.py ..
tests/IdentifierMixinTest.py .....
tests/MuscleTest.py ...
tests/NetworkTest.py .s...
tests/NeuronTest.py ................
tests/PlotTest.py ...
tests/ProfileTest.py EEEE
tests/PropertyTest.py .
tests/RDFLibTest.py ....
tests/SimplePropertyTest.py .............
tests/WormTest.py ...

==================================== ERRORS ====================================
___________________ ERROR at setup of test_adal_connections ____________________

self = <zc.lockfile.LockFile object at 0x7fead02ee160>
path = '/home/yan/PyOpenWorm/.pow/worm.db.lock'

    def __init__(self, path):
        self._path = path
        try:
            # Try to open for writing without truncation:
>           fp = open(path, 'r+')
E           FileNotFoundError: [Errno 2] No such file or directory: '/home/yan/PyOpenWorm/.pow/worm.db.lock'

../anaconda3/lib/python3.6/site-packages/zc/lockfile/__init__.py:75: FileNotFoundError

During handling of the above exception, another exception occurred:

    def setup():
>       connect(configFile='tests/data_integrity_test.conf')

tests/ProfileTest.py:11: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
PyOpenWorm/__init__.py:235: in connect
    conf.openDatabase()
PyOpenWorm/data.py:256: in openDatabase
    self.init_database()
PyOpenWorm/data.py:262: in init_database
    self.source.open()
PyOpenWorm/data.py:604: in open
    fs = FileStorage(openstr)
../anaconda3/lib/python3.6/site-packages/ZODB/FileStorage/FileStorage.py:164: in __init__
    self._lock_file = LockFile(file_name + '.lock')
.....
.....
.....
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../tests/ExampleRunnerTest.py:35: in execfile
    out.read()))
E   AssertionError: 0 != 1 : Example failed with status 1. Its output:
E   Traceback (most recent call last, import_override removed):
E     File "morpho.py", line 15, in <module>
E       P.connect('default.conf')
E     File "/home/yan/anaconda3/lib/python3.6/site-packages/PyOpenWorm/__init__.py", line 235, in connect
E       conf.openDatabase()
E     File "/home/yan/anaconda3/lib/python3.6/site-packages/PyOpenWorm/data.py", line 256, in openDatabase
E       self.init_database()
E     File "/home/yan/anaconda3/lib/python3.6/site-packages/PyOpenWorm/data.py", line 262, in init_database
E       self.source.open()
E     File "/home/yan/anaconda3/lib/python3.6/site-packages/PyOpenWorm/data.py", line 604, in open
E       fs = FileStorage(openstr)
E     File "/home/yan/anaconda3/lib/python3.6/site-packages/ZODB/FileStorage/FileStorage.py", line 164, in __init__
E       self._lock_file = LockFile(file_name + '.lock')
E     File "/home/yan/anaconda3/lib/python3.6/site-packages/zc/lockfile/__init__.py", line 81, in __init__
E       fp = open(path, 'a+')
E   FileNotFoundError: [Errno 2] No such file or directory: '/home/yan/PyOpenWorm/.pow/worm.db.lock'
==== 30 failed, 219 passed, 10 skipped, 1 xfailed, 4 error in 49.02 seconds ====

**Comment by mwatts15** [comment]
Closing this as it should be resolved with #371.
