### ISSUE TITLE
beginner issue: Followed the steps in the “README.md“, but got different results and failed to connect to the context website

### ISSUE THREAD

**Issue by meghanic** [openworm/PyOpenWorm#371]
*beginner issue*
### Hi,

I'm a begginner of the openworm，could i ask a fool question about the PyOpenWorm?

1. After installing the PyOpenWorm in ubuntu system, it shows install successfully. Then I followed the steps in the “README.md“, but got different results. The result of "aval.type.one()" is None. The result of code ”aval.connection.count('pre')“ is 0. 
2. Failed to connect to the website “http://openworm.org/entities/bio#worm0-data”.

I don't know if there is a causal relationship between the two questions. If there's no causal relationship，I don't no why the result is wrong and how to fix it.
Please help me ,thank you!!

The  following is written in the document:

```python
# Make the context
>>> from PyOpenWorm.context import Context
>>> ctx = Context(ident='http://openworm.org/entities/bio#worm0-data')

# Grabs the representation of the neuronal network
>>> from PyOpenWorm.worm import Worm
>>> net = ctx.stored(Worm)().neuron_network()

# Grab a specific neuron
>>> from PyOpenWorm.neuron import Neuron
>>> aval = ctx.stored(Neuron)(name='AVAL')

>>> aval.type.one()
'interneuron'

#show how many connections go out of AVAL
>>> aval.connection.count('pre')
86


The following is the result of mine：


>>> from PyOpenWorm.context import Context
>>> ctx = Context(ident='http://openworm.org/entities/bio#worm0-data')

>>> from PyOpenWorm.worm import Worm
>>> net = ctx.stored(Worm)().neuron_network()

>>> from PyOpenWorm.neuron import Neuron
>>> aval = ctx.stored(Neuron)(name='AVAL')

>>> aval.type.one()

>>> aval.connection.count('pre')
0

**Comment by meghanic** [comment]
When I first time execute this command on the command line，There are some errors.
pow clone git@github.com:openworm/OpenWormData.git
Now I've fixed these errors.Then retry code I've posted in this issue.I got the same result  with README.md.
Thank you for your help!

**Comment by mwatts15** [comment]
Good news! Thanks again.
