### ISSUE TITLE
Remove networkx dependency

### ISSUE THREAD

**Issue by clbarnes** [openworm/PyOpenWorm#379]
Currently, networkx is only used in the test for `Context.Network.as_networkx`, which is skipped because the method under test is not implemented (presumably related to https://github.com/openworm/PyOpenWorm/issues/253 ).

However, PyOpenWorm still has a hard dependency on networkx 1.9, which saw its last release 4 years ago. It seems pretty likely that anyone wanting to do stuff with a connectome might already be using networkx; in this case POW is constraining the downstream environment for no reason.

In the short term, I propose removing the dependency and commenting out the test (I can do this). I can also have a crack at implementing as_networkx for networkx 2+, if it's as simple as turning `Connection`s and `Neuron`s into a MultiDiGraph!

**Comment by clbarnes** [comment]
In general, PyOpenWorm uses hard requirements in its setup.py, which is not recommended for library packages. Install requirements should be as loose to constrain downstream usage as much as possible, but (more) deterministic builds for developers can be achieved with a requirements.txt with hard versions.

**Comment by mwatts15** [comment]
Thanks @clbarnes . This actually just needed to be removed. Translation to NetworkX should actually be handled with a DataTranslator.
