### ISSUE TITLE
git command error

### ISSUE THREAD

**Issue by moanra** [openworm/PyOpenWorm#398]
Hello,
After installing I got this error to get start to connect to the database. You can see the picture below. What is your advice. Thanks
![git_command_error](https://user-images.githubusercontent.com/48910563/55602388-984ce380-5765-11e9-8b21-ffb831c84039.PNG)

**Comment by mwatts15** [comment]
Thanks for the report. Can you run the `git clone --progress -v git@github.com:openworm/OpenWormData.git .\.pow` command it shows at the bottom to see if there's a distinct error message attached to that?

**Comment by moanra** [comment]
Thanks you so much.
![remote access ok](https://user-images.githubusercontent.com/48910563/55681803-cc253600-592a-11e9-8495-f66e570b50d9.PNG)

**Comment by mwatts15** [comment]
Ah, OK. So, it looks like you have a pass-phrase on your SSH key: that must be the error then, I'll see if we can forward that prompt to the user.

**Comment by mwatts15** [comment]
Opted to just change the recommended clone URL.

**Comment by moanra** [comment]
![connection](https://user-images.githubusercontent.com/48910563/55729823-2a2f4780-5a17-11e9-9317-dd16286f69da.PNG)
