### ISSUE TITLE
Update install instructions & test examples

### ISSUE THREAD

**Issue by pgleeson** [openworm/PyOpenWorm#399]
@mwatts15 I'm testing the latest dev branch and having trouble running some of the standard examples. Can you add info re "pow clone https://github.com/openworm/OpenWormData.git" to INSTALL.md (or consolidate that into to the main Readme...) and any other steps?

Also getting errors like:
```
  File "NeuronBasicInfo.py", line 20, in <module>
    from OpenWormData import BIO_ENT_NS
```

**Comment by mwatts15** [comment]
Hi, @pgleeson . What is the error? I don't get any error for that line of code.

**Comment by pgleeson** [comment]
There seems to be another Python module in the directory https://github.com/openworm/PyOpenWorm/tree/dev/OpenWormData, which is what's required at the line https://github.com/openworm/PyOpenWorm/blob/eafd7cb4463e84a4bca21b34eecf317d86a34e0e/examples/NeuronBasicInfo.py#L20

However, this doesn't get installed when `python setup.py install` gets called, it's just the module at https://github.com/openworm/PyOpenWorm/tree/dev/PyOpenWorm.

**Comment by mwatts15** [comment]
Strangely, `python setup.py sdist` was still including the OpenWormData package even though it's no longer passed to the `setup` function in `packages`. In any case, I've removed references to OpenWormData and removed the `__init__.py`.

I think the documentation is sufficient for installation, but I've started a little about `pow`.

**Comment by pgleeson** [comment]
Great, thanks. Works fine for me now.
