### ISSUE TITLE
Loading neurons with Neuron().load() is very slow

### ISSUE THREAD

**Issue by slarson** [openworm/PyOpenWorm#42]
Tests are incredibly slow:

```
-----------------------------------------------------------------
Testing with tests/test_ZODB.conf
Ran 96 tests in 274.587s

OK (SKIP=8)
-----------------------------------------------------------------
```

Simple functions are incredibly slow (each takes more than 90 seconds to complete)

```
>>> net.aneuron('AVAL').connection.count('either',syntype='gapjunction')
80
>>> len(set(net.neurons()))
302
```

These are very fast in master

Asserts() is incredibly slow (more than 10 minutes to complete final command & then I got tired of waiting):

```
>>> e = P.Evidence(author='Sulston et al.', date='1983')
>>> e.asserts(P.Neuron(name="AVDL").lineageName("AB alaaapalr"))
asserts=lineageName=AB alaaapalr
>>> e.save()
>>> e0 = P.Evidence(author='Sulston et al.', date='1983')
>>> list(e0.asserts())
...? #what's the output?  Can't be bothered to wait for it...
```

**Comment by slarson** [comment]
Reopening since @travs reported it again on #90

**Comment by slarson** [comment]
I want to focus this issue down to one particular operation that we have in our current readme:

len(set(P.Neuron().load()))

This thing has been running for a long long time (more than 5 minutes) on my laptop with no hope of returning.  As stated above, we are putting this out as a basic way to count how many neurons are in the system, so it needs to return in at least several seconds, not minutes.

I can imagine a SPARQL query that should be able to pull this out quickly so we should look at how to optimize this part of the system

**Comment by mwatts15** [comment]
You'll see in my pull request #82 that I added a set of methods that use queries with smaller patterns.

The difference between the queries is this:
Current Pattern:
```
?Neuronab71cc3e2f6c0c3f <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://openworm.org/entities/Neuron> .
?Neuronab71cc3e2f6c0c3f <http://openworm.org/entities/Cell/lineageName> ?Cell_lineageNamedf92353f91b15f3f .
?Cell_lineageNamedf92353f91b15f3f <http://openworm.org/entities/SimpleProperty/value> ?lineageName .
?Neuronab71cc3e2f6c0c3f <http://openworm.org/entities/Cell/name> ?Cell_namee8b66a3fa15bea3e .
?Cell_namee8b66a3fa15bea3e <http://openworm.org/entities/SimpleProperty/value> ?name .
?Neuronab71cc3e2f6c0c3f <http://openworm.org/entities/Cell/divisionVolume> ?Cell_divisionVolumefbf6e73ec904ca3e .
?Cell_divisionVolumefbf6e73ec904ca3e <http://openworm.org/entities/SimpleProperty/value> ?divisionVolume .
?Neuronab71cc3e2f6c0c3f <http://openworm.org/entities/Cell/description> ?Cell_description5967e23ec58a063e .
?Cell_description5967e23ec58a063e <http://openworm.org/entities/SimpleProperty/value> ?description .
?Neuronab71cc3e2f6c0c3f <http://openworm.org/entities/Neuron/type> ?Neuron_type9d9c783fc5da3c3e .
?Neuron_type9d9c783fc5da3c3e <http://openworm.org/entities/SimpleProperty/value> ?type .
?Neuronab71cc3e2f6c0c3f <http://openworm.org/entities/Neuron/receptor> ?Neuron_receptorbad0ed3d29a7243f .
?Neuron_receptorbad0ed3d29a7243f <http://openworm.org/entities/SimpleProperty/value> ?receptor .
?Neuronab71cc3e2f6c0c3f <http://openworm.org/entities/Neuron/innexin> ?Neuron_innexin0a65193f053e0e3e .
?Neuron_innexin0a65193f053e0e3e <http://openworm.org/entities/SimpleProperty/value> ?innexin .
?Neuronab71cc3e2f6c0c3f <http://openworm.org/entities/Neuron/neurotransmitter> ?Neuron_neurotransmitteraa9e163f3e9f143e .
?Neuron_neurotransmitteraa9e163f3e9f143e <http://openworm.org/entities/SimpleProperty/value> ?neurotransmitter
```
New Pattern:
```
?Neuron6b4b4b3f18099f3d <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://openworm.org/entities/Neuron>
```

The first query pattern, of course, yields all of the different ways that each `Neuron` node can be linked to its different `neurotransmitter` nodes, `type` nodes, etc. This is opposed to the second which yields nodes of type `Neuron`. So, it's something on the order of the product of the number of values of the properties versus something linear, not considering index scans/lookups that also have to occur in order to return the other properties.

I've created a [gist](https://gist.github.com/mwatts15/03de5258bd3d9483eb38) with the script used to generate the graph patterns above which also has a patch for a3087ad07918f0746c4fcf3d17bc65ae946cc259 necessary to run the script without error.

**Comment by slarson** [comment]
@mwatts15 Brilliant!  Will take a look!

**Comment by slarson** [comment]
@mwatts15 hmm I'm confused though.  Because I've been running this since #85 got merged and it is still slow... I would have thought the more efficient queries would have already improved the performance.  What steps are you recommending beyond #85 to improve this?

**Comment by slarson** [comment]
This example was also in the readme, removing for now, let's put back in when this is fixed.

To get any object's possible values, use load()::
```python
  >>> list(P.Neuron().load())
  [
   ...
   Neuron(lineageName=, name= Neighbor(), Connection(), type=, receptor=, innexin=),
   Neuron(lineageName=, name= Neighbor(), Connection(), type=, receptor=VGluT, innexin=),
   Neuron(lineageName=, name= Neighbor(), Connection(), type=, receptor=EAT-4, innexin=),
   Neuron(lineageName=, name= Neighbor(), Connection(), type=, receptor=, innexin=),
   Neuron(lineageName=, name= Neighbor(), Connection(), type=, receptor=, innexin=),
   Neuron(lineageName=, name=Neighbor(), Connection(), type=, receptor=, innexin=),
   Neuron(lineageName=, name=Neighbor(), Connection(), type=, receptor=FLP-1, innexin=),
   Neuron(lineageName=, name=Neighbor(), Connection(), type=, receptor=, innexin=),
   ...
  ]
  # Properties are a little different
  >>> next(P.Neuron().receptor.load())
  receptor=INS-1;FLP-6;FLP-21;FLP-20;NLP-21...

```

**Comment by mwatts15** [comment]
@slarson, the second query from my comment gets run with:
```
from __future__ import print_function
import PyOpenWorm as P

P.connect("default.conf", do_logging=True)
for x in P.Neuron().load0():
    print(x)
```

**Comment by mwatts15** [comment]
I have replaced `DataObject::load` with `load0` in the alpha0.5 branch of my fork, which is the subject of #95. I have about .366 seconds for `list(P.Neuron().load())` on that branch. Acceptable results should be fairly independent of the machine profile, but I can provide my system specs to go with the time if we still have very different results for that query on my alpha0.5 fork.

**Comment by mwatts15** [comment]
I just ran this on dev with Python 3.4:
```
import PyOpenWorm
from time import time
PyOpenWorm.connect('PyOpenWorm/default.conf')
t0 = time()

print("Neurons:")
print(", ".join(sorted(PyOpenWorm.Neuron().name.get())))

print("Receptors:")
print(", ".join(sorted(PyOpenWorm.Neuron().receptor.get())))
tot = time() - t0
print ("Took {} seconds".format(tot))
```
With this output:
```Neurons:
ADAL, ADAR, ADEL, ..., VD9
Receptors:
ACR-13, ACR-14, ..., UNC-8
Took 0.49202728271484375 seconds
```
Again, not ideal, but also not "very slow", so I'm closing this one.
