### ISSUE TITLE
Integrate doctest with unit tests

### ISSUE THREAD

**Issue by mwatts15** [openworm/PyOpenWorm#45]
Doctest may be helpful in keeping the examples in documentation up-to-date with the source code.

Doctest should execute as part of the normal unit testing.

**Comment by slarson** [comment]
@gsarma -- can you look into implementing this?  As there are several examples in the readme that are not correctly working, this could be a huge way to keep everything in sync.

**Comment by gsarma** [comment]
Will take a look tomorrow with @travs

**Comment by slarson** [comment]
Fixed by #110
