### ISSUE TITLE
Port PyOpenWorm to python3

### ISSUE THREAD

**Issue by clbarnes** [openworm/PyOpenWorm#66]
## Advantages:
- Other parts of the project, such as movement_validation, are built in python3 - consistency is good.
- It seems unlikely that python3 will be abandoned as a failed experiment at this point - given we want the usership of PyOpenWorm to increase over time, it seems better to write forward-compatible than backward-compatible code.
- By importing from **future**, some python3-style code can be interpreted in python2: you can't do the same to interpret python2-style code in python3.
- It's a newer version - all the changes which have been made have presumably been made for a reason, resulting in either cleaner, faster, or more robust code.
## Difficulties:

There may well be 3rd party packages which don't support python 3... yet. Again, I find it highly unlikely that as time goes on, there will be any important piece of functionality offered by py2 packages which won't have a counterpart in py3. RDFlib and sqlite3 both seem to be supported. libNeuroML may not be, but having a dig through that code there doesn't seem to be any packages which wouldn't support it.

A 'port to python3' issue is the sort of thing which should be on the backlog of absolutely any maintained python project. Currently, it is just on the backlog, and under 'ideas'- surely we plan to do this at some point in the future, and planning for the future is what backlogs are for!

See also: [Python 3 Porting HOWTO](https://docs.python.org/3/howto/pyporting.html)

**Comment by mwatts15** [comment]
Working on this now. I'll keep compat with 2.7 where possible.

**Comment by mwatts15** [comment]
Port to Python 3 is done and merged into dev.
