### ISSUE TITLE
Neuron objects with no type attributes

### ISSUE THREAD

**Issue by travs** [openworm/PyOpenWorm#70]
When using the API no type() is returned for most Neurons().

It is not clear whether this is on the db or API end. 

This issue is already mentioned in #62 but I am raising it here to further channel our discussions.

**Comment by slarson** [comment]
@travs great observations.  Curious why PHAL is the only one with a type....?

**Comment by shekhov** [comment]
This is something we can put into the test actually:
Try this:

    import rdflib    
    import pprint
    g = rdflib.Graph ("ZODB")
    g.parse ("OpenWorm/WormData.n3")
    ntype_query = "SELECT ?type ?value WHERE {?type a <http://openworm.org/entities/Neuron_type>. \
    '?type <http://openworm.org/entities/SimpleProperty/value> ?value}"
    ntype_r = g.query (ntype_query).result
    len (ntype_r)
    pprint.pprint (ntype_r)

And if I did not make a type here it should give now only "sensory" and "motor" neuron types. We also can then easily look what are the neurons with types 

    type_neurons_query = "SELECT ?name_value ?type_value WHERE {?type a <http://openworm.org/entities/Neuron_type>." \
                  "?type <http://openworm.org/entities/SimpleProperty/value> ?type_value." \
                  "?cell <http://openworm.org/entities/Neuron/type> ?type." \
                  "?cell <http://openworm.org/entities/Cell/name> ?name." \
                  "?name <http://openworm.org/entities/SimpleProperty/value> ?name_value."\
                  "?name a <http://openworm.org/entities/Cell_name>}"
    pprint.pprint (g.query (type_neurons_query).result)

Which will print next:
>[(rdflib.term.Literal(u'PHAL'), rdflib.term.Literal(u'sensory')),
 (rdflib.term.Literal(u'DD5'), rdflib.term.Literal(u'motor'))]

All other neurons are having empty type variable in the nodes, which are looking something like Travis showed (there are 610 of them)

**Comment by slarson** [comment]
I'd expect that the data is going in wrong in the first place from the database in [insert_worm.py](https://github.com/openworm/PyOpenWorm/blob/alpha0.5-slarson/OpenWormData/scripts/insert_worm.py#L168).  Looks like we need to work up tests that pull from the SQL Lite database and compare to what ends up in PyOpenWorm.  There may be some confusions on how to resolve the structure of the SQLite database that got built into this method.

**Comment by slarson** [comment]
I believe this is fixed as well with #82
