### ISSUE TITLE
Facts need associated evidence() in the db

### ISSUE THREAD

**Issue by travs** [openworm/PyOpenWorm#75]
Just further channeling our discussions with this issue (originally mentioned in #62).

I am taking _facts_ here to mean `DataObject` objects that are not `Evidence` objects.

When we say "facts must have associated evidence" we are saying that every `DataObject` must have an associated `Evidence` node, unless the `DataObject` is an `Evidence` object itself.

Does this sound reasonable?

blocked by #160 (adding Evidence should be done under #160)

**Comment by slarson** [comment]
@travs Hmm -- here's the thing.  A fact is actually inclusive of a data object and a relationship to another data object.  So a fact is not simply "AVAL" the data object, the fact is that "AVAL" has some relationship to "AVAR", like a gap junction connection, for example.  In RDF, this should mean that every triple has evidence for it.  

The way @mwatts15 has wrapped the graphs has left me a bit unsure about what at the object level needs to be associated with the Evidence object, but I suspect looking at the examples dealing with Evidence would make that clear.

**Comment by mwatts15** [comment]
For the method I use to attach evidence, there are certain resources in the graph which correspond to, really, arbitrary `DataObjects`. I was fairly uncertain in the design of this as far as going in the "reverse" direction from an object to get evidence. So you you can list all of the `Evidence` objects, look at what they have on the other ends of their `asserts` property, and a motivated human can get some idea of where that data came from.

**Comment by travs** [comment]
So I just did a couple queries and it looks like all of the Evidence in the db goes to support a small number of `DataObjects`, which themselves map to thousands of `Cells`, `Neurons`, etc.

```python
import rdflib as R
g = rdflib.Graph()
g.parse ("OpenWorm/WormData.n3", format='n3')

g.query('SELECT ?s WHERE {?e a <http://openworm.org/entities/Evidence>. ?e <http://openworm.org/entities/Evidence/asserts> ?a. ?a <http://openworm.org/entities/SimpleProperty/value> ?s}').result
```

Everything that is returned has the *same URI*.

If you now do a query for that URI, you find a single node of course. In my case:

```python
g.query('SELECT ?p WHERE{<http://openworm.org/entities/Worm/ca57c2c6f9cbe28a29dc83b485068cf2daf78ffcfb5ec972f0d88303> a ?p}').result
```
This means that all `Evidence` objects point back to the overarching `Worm`.

Let's take a peek at the `Worm`'s properties:

```python
g.query('SELECT ?p WHERE{?w a <http://openworm.org/entities/Worm>. ?w ?p ?v}').result
```

Now let's look into one of the properties, say the `cell` property:

```python
g.query('SELECT ?v WHERE{?w a <http://openworm.org/entities/Worm>. ?w <http://openworm.org/entities/Worm/cell> ?v}').result
```

`Worm_cell` properties? Looking into these  little further (I won't put the queries here to save space), I found that each `Worm_cell` holds hundreds of references to other nodes.
For example, the first `Worm_cell` in the list refers to `Cell` objects, while the second refers to `Neuron`s and the third to `Muscles`. After the first three `Worm_cell`s the rest refer to the *exact same* set of `Cells` that the first `Worm_cell` does, leading me to believe they may be redundant references.

I have not looked into the other properties of the `Worm`, but they may suffer from the same redundancy.

Since the `Evidence` is meant to support *relationship* nodes rather than straight up `Cells`, even by this transitive route (`Evidence -> Worm -> Worm_cell -> Cell`) there does not seem to be any `Evidence` in the graph that does this.

**Next steps?**

* If there is already Evidence in the db that is supposed to be attached to relationship nodes, then we need to take a look at how the graph is constructed to make sure these are included.

* As I understand it, the `Evidence` class is not being used in the correct capacity, so we can adjust that when we build the `Worm` in `insert_worm.py` if that is the case

* We can incorporate queries similar to the above into our sanity tests. 

* Maybe we should make another property `asserted_by` (?) that we can attach to nodes that have supporting evidence. This would make queries in the other direction (`Object -> Evidence`) a lot easier, as well as the mentioned sanity test.

What do you guys think?

**Comment by gsarma** [comment]
@travs and I added tests for neuron and muscle evidence- there is nothing for either category.

**Comment by slarson** [comment]
@gsarma link? :)

**Comment by gsarma** [comment]
Whoops!  It's on my fork:
https://github.com/gsarma/PyOpenWorm/commit/9116c483995871d220cc31a0a8cef29138593dac

I'll issue a pull request after we add the remaining ones- we've been spending some time discussing general PyOpenWorm issues (some of which we've raised).

**Comment by travs** [comment]
Solving https://github.com/openworm/PyOpenWorm/issues/176 will feed into this

**Comment by mwatts15** [comment]
Reclassifying this as data-quality issue rather than a bug.

**Comment by mwatts15** [comment]
Closing this issue since the data sources in OpenWormData do have Evidence objects associated with them.
