### ISSUE TITLE
Add test to test.py that runs insert_worm.py and serialize_it.py and runs data tests on output

### ISSUE THREAD

**Issue by slarson** [openworm/PyOpenWorm#79]
We might consider adding a test that runs insert_worm.py and serialize_it.py so that it is running tests on whatever insert_worm generates, plus it verifies that insert_worm.py is working.

**Comment by travs** [comment]
This is a good idea. Do you think we should add this at the start of `test.py`, or should we make a shell script that jumps around and does all this, and then runs `test.py`?

I can help make either, just wondering which makes most sense.

**Comment by slarson** [comment]
@travs I'd say at the start of test.py so it is all automated and can all be executed by Travis-CI .  Thanks for asking!

**Comment by mwatts15** [comment]
I'm not in favor of putting this in `test.py` for two reasons:

- It would lengthen the time it takes to run the tests to completion and discourage developers from running the tests on a regular basis when making changes which is an extremely valuable tool.
- `insert_worm.py` is not and never was meant to be permanent and does not demand testing like the PyOpenWorm Python module. It is only a means of translating other data sources into PyOpenWorm. In the long term, we will only be testing the checked-in data (i.e., `WormData.n3`), verifying it against externally agreed-upon facts, as we are doing now in the `DataIntegrityTest` test case.

At this stage, the developer is obliged to run `insert_worm.py` if he makes a change to that script, the data model, the database format, or the serialization, but these changes should not occur often, so `insert_worm.py` should not be run as a matter of course.
