### ISSUE TITLE
Receptors associated with cells are not the ones expected

### ISSUE THREAD

**Issue by slarson** [openworm/PyOpenWorm#80]
As seen in #44 

I'd expect that the data is going in wrong in the first place from the database in [insert_worm.py](https://github.com/openworm/PyOpenWorm/blob/alpha0.5-slarson/OpenWormData/scripts/insert_worm.py#L168).  Looks like we need to work up tests that pull from the SQL Lite database and compare to what ends up in PyOpenWorm.  There may be some confusions on how to resolve the structure of the SQLite database that got built into this method.

**Comment by mwatts15** [comment]
The Relation code for neuropetide (354) was mistaken for the receptor code (361) in [insert_worm.py](https://github.com/openworm/PyOpenWorm/blob/alpha0.5-slarson/OpenWormData/scripts/insert_worm.py#L186).

**Comment by slarson** [comment]
@mwatts15 thanks for that -- fixed in #81
