### ISSUE TITLE
Clean up tests dir?

### ISSUE THREAD

**Issue by travs** [openworm/PyOpenWorm#83]
Would it be safe to remove some of the testscripts and `.conf` files we're not using in `tests/` before pushing to master?

Are we actually using any of them besides `test.py`?

**Comment by mwatts15** [comment]
As far as what uses what:

Travis-CI uses `runtests.sh` which runs the tests with each of the configurations given in `tests/test_*.conf`. Knowing that the tests complete successfully under multiple configurations is valuable.

`test_data.py` has data for a couple of tests [here](https://github.com/openworm/PyOpenWorm/blob/alpha0.5-slarson/tests/test.py#L1043) and [here](https://github.com/openworm/PyOpenWorm/blob/alpha0.5-slarson/tests/test.py#L1016).

`trix.xml` has been supplanted by `test_data.py` (it was initially moved into the tests directory at ef457cb1fe35a777054fbc102181b3f5a71abfff, but it should have been deleted).

`testl.conf` is used in a scalability test in `integration_test.py`.

On another note: `integration_test.py` is more properly `acceptance_test.py` in that the tests are meant for ["functional testing of a user story by the software development team during the implementation phase"](https://en.wikipedia.org/wiki/Acceptance_testing#Acceptance_testing_in_extreme_programming). That was a naming error on my part.

As for safety: if none of the tests break (locally or on Travis-CI), then it's okay to remove data files. `integration_test.py` should be cleaned up, the name changed, and actually run.

**Comment by slarson** [comment]
I agree!
