### ISSUE TITLE
Change source of upload_synapses() in insert_worm.py from DB to NeuronConnect.xls

### ISSUE THREAD

**Issue by slarson** [openworm/PyOpenWorm#87]
[insert_worm.py](https://github.com/openworm/PyOpenWorm/blob/alpha0.5/OpenWormData/scripts/insert_worm.py#L204) imports external content into PyOpenWorm.  upload_synapses() reads from the SQLlite DB.  We have come to doubt the origins of the original synapse information that went into this DB, after performing comparisons with the connectivity spreadsheet [online at WormAtlas](http://www.wormatlas.org/neuronalwiring.html#Connectivitydata) (sec 2.1).  To have maximal authoritative provenance for the connectivity, let's change this method instead to read this spreadsheet directly and import it to PyOpenWorm, cutting out the SQLliteDB middle man.

Let's also add the Evidence tag for all connectivity statements to point to this page / spreadsheet on WormAtlas.

**Comment by travs** [comment]
Notice that I have updated `WormData.n3` in 9a65112. This is the result of running `python insert_worm.py` and `python serialize_it.py` in succession, which should be fixed after we get a script to do what @slarson said in #79

**Comment by slarson** [comment]
Closed by #89 !! :)
