### ISSUE TITLE
Repair example for finding which neurons have which receptors

### ISSUE THREAD

**Issue by slarson** [openworm/PyOpenWorm#91]
This was in the readme: 

See what neurons express some receptor::
```python
  >>> n = P.Neuron()
  >>> n.receptor("TH")
  receptor=TH

  >>> s = set(x.name.one() for x in n.load()) 
  >>> s == set(['CEPVL','CEPVR','PDEL','PDER','CEPDR'])
  True

```

But it doesn't work.  Instead s gets set to:

```
set([])
```

It would be really cool if this actually worked !

**Comment by mwatts15** [comment]
"TH" is given as a neuropeptide in the `celegans.db` sqlite3 database. This is related to issue #80.
Here's a patch based on a3087ad07918f0746c4fcf3d17bc65ae946cc259: https://gist.github.com/mwatts15/d746b054cf49be6a94c1

**Comment by slarson** [comment]
Looks like it is fixed via not failing in the doctests.
