### ISSUE TITLE
Update the docs to match implemented API

### ISSUE THREAD

**Issue by travs** [openworm/PyOpenWorm#94]
Since MergingWithMaster day is coming up I tried out some of the commands from the API.
I realized after I went through the API that #27 exists already, :expressionless: so I struck through the issues I found that were caused by unimplemented API.

Started with:
```python
from PyOpenWorm import *
connect('default.conf')
```

(Is there a way to get to PyOpenWorm's `worm.db` from anywhere, to avoid having to make a new `.conf` file that has the relative `.db` position for every directory I want to run PyOW from?)

#### API inconsistencies (?)

- [`Worm().cells()`](http://pyopenworm.readthedocs.org/en/alpha0.5/api.html#worm-cells-population) does not return anything.
- The [first example](http://pyopenworm.readthedocs.org/en/alpha0.5/api.html#evidence-asserts-relationship-relationship-relationship) here returns an error on the line `c = Connection(pre=n1,post=n2,class="synapse")` due to outdated syntax.
- The same line as above appears [here](http://pyopenworm.readthedocs.org/en/alpha0.5/api.html#evidence-asserts-listof-relationship) as well.
- Tried `Relationship().pull()` for [this](http://pyopenworm.readthedocs.org/en/alpha0.5/api.html#relationship-pull-class-python-class-method-name-string-setof-relationship), but it didn't work ('Relationship' object has no attribute 'pull')
- [This example](http://pyopenworm.readthedocs.org/en/alpha0.5/api.html#relationship-pull-class-python-class-method-name-string-setof-relationship) doesn't work as it is written. It works if you get the Cell object via `net.aneuron('ADAL')` where `net` is the Network from `Worm().neuron_network()`.
- [This example](http://pyopenworm.readthedocs.org/en/alpha0.5/api.html#cell-parentof-listof-cell) does not work for me either. It returns a `generator` object, and wrapping it in `list` returns an empty list.
- ~~[This](http://pyopenworm.readthedocs.org/en/alpha0.5/api.html#cell-divisionvolume-quantity) seems incomplete.~~
- I don't know enough about [this](http://pyopenworm.readthedocs.org/en/alpha0.5/api.html#cell-divisionvolume-volume-quantity-relationship) to say if it is working or not, but it produces no errors.
- ~~Can't get morphology using [this part of the API](http://pyopenworm.readthedocs.org/en/alpha0.5/api.html#cell-morphology-morphology) with `net.aneuron('ADAL').morphology`.~~
- [This](http://pyopenworm.readthedocs.org/en/alpha0.5/api.html#neuron-neighbor-listof-neuron) suffers from the same slowness as `Neuron.connection()` from #90.
- ~~Error from [this](http://pyopenworm.readthedocs.org/en/alpha0.5/api.html#muscle-receptor-listof-receptor). Got a Muscle by doing`mvl06 = list(Worm().muscle())[0]`, then tried `mvl06.receptor()`. `Muscle` object has no attribute 'receptor'~~
- ~~The same for [this](http://pyopenworm.readthedocs.org/en/alpha0.5/api.html#muscle-receptor-receptor-receptor-relationship) as well.~~
- [Here](http://pyopenworm.readthedocs.org/en/alpha0.5/api.html#population) population is not defined.
- [This](http://pyopenworm.readthedocs.org/en/alpha0.5/api.html#population-filtercells-filters-listof-pairof-unboundmethod-methodargument-population) doesn't work either, because of above.
- I believe [these](http://pyopenworm.readthedocs.org/en/alpha0.5/api.html#connection-pre-neuron-post-neuron-strength-integer-ntrans-neurotransmitter-type-connectiontype) arguments into the `Connection` constructor are supposed  to be updated (`pre_cell` instead of `pre`, etc.)
- [No attribute 'type'](http://pyopenworm.readthedocs.org/en/alpha0.5/api.html#connection-type-connectiontype) for the same reason as above, I suspect.
- The same for `strength`, `neurotransmitter` and `ConnectionType`.

**Comment by mwatts15** [comment]
Hi @travs. The document you reference was a proposal that mostly hasn't been modified since moving into the implementation phase, so it may not entirely reflect what I, at least, intend to support with PyOpenWorm for the next release. Is this ticket meant to propose an update to that document to reflect the state of the API as it has been implemented or to propose changes to what has been implemented in order to bring it into line with that document?

**Comment by travs** [comment]
The first one.
I can definitely help update the docs before we merge alpha0.5 into master, I'm just not familiar with Sphinx, so I'll have to brush up on that as we start.

**Comment by mwatts15** [comment]
I think the most that document needs is a pointer back to the live API as generated from the docstrings in source code.

**Comment by travs** [comment]
Probably lol. Where is the live API?

**Comment by mwatts15** [comment]
http://pyopenworm.readthedocs.org/en/alpha0.5/

**Comment by slarson** [comment]
@travs Awesome list of things you tested out!!!  So cool.  You make good points on the documentation side of this.  I'll include this one in the alpha0.5 critical path.

**Comment by mwatts15** [comment]
Related to #98: The autodocs generated documentation is already present on the main page of the docs. Rather than delete the draft, I would create a document summarizing the design considerations that went into our current iteration and link to the draft from there. The draft itself could hold a link to the most recent docs to resolve residual confusion.

**Comment by travs** [comment]
Sounds like a good idea to me
