### ISSUE TITLE
No module named 'six'

### ISSUE THREAD

**Issue by travs** [openworm/PyOpenWorm#96]
**alpha0.5 branch**

When running `OpenWormData/scripts/insert_worm.py` or `serialize_it.py` the interpreter complains about not having `six`. 

Just mentioning this here as a reminder for when #79 gets implemented and (perhaps) fails on CI.

**Comment by mwatts15** [comment]
Do you have `six` installed? It's normally pulled in as a transitive dependency of one or more of our direct dependencies.

**Comment by travs** [comment]
Had to install it with `pip` then everything was fine.

This was after doing `python setup.py install` in a fresh virtualenv.

**Comment by mwatts15** [comment]
You're saying that `six` wasn't installed after `python setup.py install`? In that case, does `six` show up anywhere in the output from the install, either showing as being installed or showing error?

**Comment by travs** [comment]
Just tried reinstalling in another two new virtualenvs and it works perfectly with either `python setup.py install` or `python setup.py develop`, and since I can't go back far enough in history to see what happened during the install without `six`, I have no idea what went wrong. :confused: 

Going to close this until someone else reports something similar.
