### ISSUE TITLE
Remove unnecessary git files to reduce size of repo

### ISSUE THREAD

**Issue by VahidGh** [openworm/PyOpenWorm#99]
When cloning this repo to the local station, the size of the repo is ~100 MB, while the required files (when downloading .zip file) are just ~2 MB.
I guess the problem is with git history files.

**Comment by mwatts15** [comment]
Hi Vahid,

Yes, there are some binaries that have been checked in and a large text
file that's had several global modifications. I intend to fork PyOpenWorm
and do a history rewrite to delete references to the files that are gone
before the 1.0 release.

On Sun, Mar 15, 2015 at 2:41 AM, Vahid Ghayoomi <notifications@github.com>
wrote:

> When cloning this repo to the local station, the size of the repo is ~100
> MB, while the required files (when downloading .zip file) are just ~2 MB.
> I guess the problem is with git history files.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openworm/PyOpenWorm/issues/99>.
>



-- 
Cheers,

Mark W.

**Comment by VahidGh** [comment]
Hi Mike, 
Great, so waiting for R1 :)

**Comment by slarson** [comment]
Doing some research into this, we found this answer for doing this work:

https://stackoverflow.com/questions/11050265/remove-large-pack-file-created-by-git

**Comment by slarson** [comment]
This answer also relevant because we need to find the big files: https://stackoverflow.com/questions/10622179/how-to-find-identify-large-files-commits-in-git-history

**Comment by mwatts15** [comment]
Yes, I used largestFiles.py when I did this before. It rewrites history, so none of the commits after 40c76eef687cbe0743585b9f8178969ff015467c would match up in the new branch compared to GitHub. That's just to say it should be the last step before release.

**Comment by slarson** [comment]
It. All. Comes. Down. To. This :)

**Comment by slarson** [comment]
![screenshot 2015-06-15 16 35 40](https://cloud.githubusercontent.com/assets/1037756/8173033/ad80eb4c-137c-11e5-9277-dd8ebed44029.png)

**Comment by slarson** [comment]
fixed by #150

**Comment by slarson** [comment]
Unfortunately, just recloned today, and the clone is still ~100 MB... :-/

**Comment by slarson** [comment]
Rats even with #156 this is still an issue...
![screenshot 2015-06-19 16 49 58](https://cloud.githubusercontent.com/assets/1037756/8264982/5fe405ca-16a3-11e5-8bb2-f4ed82c98c35.png)

**Comment by slarson** [comment]
![screenshot 2015-06-20 12 41 04](https://cloud.githubusercontent.com/assets/1037756/8268958/bf4d327e-1749-11e5-984f-ae59e41994ff.png)

FIXED!
